### PR TITLE
CB-21987 Relax custom configs runtime check

### PR DESCRIPTION
**Pull request by aakashshankar**
See detailed description in the commit message.

### CODE REVIEW

**Review by lajosrodek — APPROVED** [review]
LGTM

**Comment by lacikaaa** [comment]
please add a bit more info to the commit message

**Comment by aakashshankar** [comment]
> please add a bit more info to the commit message

Added more info

**Comment by lacikaaa** [comment]
as I see you have removed this runtime version check, but I've the feeling that this was added originally to ensure the custom configs are applied to the right version. I can imagine that the check was at the wrong place here, but still it should be present during cluster creation, shouldn't it?

**Comment by aakashshankar** [comment]
>as I see you have removed this runtime version check, but I've the feeling that this was added originally to ensure the custom configs are applied to the right version. I can imagine that the check was at the wrong place here, but still it should be present during cluster creation, shouldn't it?

The runtime check was added initially to make this less error-prone and apply configs to the appropriate runtime. However, it was decided to remove this to unblock the customer. A long term solution is required to ensure that the version check is updated after runtime upgrade. This will include a check during cluster creation

**Comment by lacikaaa** [comment]
can it cause any issues for other customers that this check is removed?

**Comment by aakashshankar** [comment]
No, this won't cause any issues. Any configs created will still be applied onto the cluster. The version check is also skipped in case the config set is not necessarily linked to a runtime

**Review by lacikaaa — APPROVED** [review]

**Comment by aakashshankar** [comment]
#14964

**Pull request merged**
