### PR TITLE
CB-12218 Change default location for NiFi and NiFi Registry working d…

### PR DESCRIPTION
**Pull request by vbrodetskyi**
…irectories. Changed default working directories for NiFi and NiFi Registry to make possible datahub upgrade for future versions.

See detailed description in the commit message.

### CODE REVIEW

**Review by doktoric — APPROVED** [review]

**Comment by lajosrodek** [comment]
None of those providers have any unit tests. Afraid to ask but will do nevertheless: Shall not we add some tests for those guys as well? 😃

**Comment by doktoric** [comment]
@lajosrodek I just planning to write unit test for this

**Review by adenes — APPROVED** [review]
LGTM, thanks @vbrodetskyi

**Comment by vbrodetskyi** [comment]
@doktoric @lajosrodek could you please merge current PR?

**Pull request merged**
