### PR TITLE
CB-15710 Add java.io.tmpdir property for NiFi. Added property java.ar…

### PR DESCRIPTION
**Pull request by vbrodetskyi**
…g.7, to set additional java argument java.io.tmpdir for NiFi process.

See detailed description in the commit message.

### CODE REVIEW

**Comment by lnardai** [comment]
Change looks okay, but we'll only merge this after the next hotfix in line is merged:
https://github.com/hortonworks/cloudbreak/pull/12085

**Review by lajosrodek — APPROVED** [review]

**Comment by lajosrodek** [comment]
@vbrodetskyi Just a few sanity checks:
* Does this really have to land in CB 2.51 instead of master (2.52)?
* Is there possibly any prerequisite regarding runtime version support (I mean possibly requiring some recent build of 7.2.14)?

**Comment by vbrodetskyi** [comment]
> @vbrodetskyi Just a few sanity checks:
> 
> * Does this really have to land in CB 2.51 instead of master (2.52)?
> * Is there possibly any prerequisite regarding runtime version support (I mean possibly requiring some recent build of 7.2.14)?

@lajosrodek  Richard told me that i just need to create PR for 2.51.0. After that it will be merged to master. 
> ping Laszlo to merge to the relesase branch and we will merge back
> no need for master branch pr

No, there is not any requirement on CM/CDH version, for this property. Only CFM-2.2.4.0 required. It should be default CFM version for CDP 7.2.14, so i think everything should be fine.

**Comment by vbrodetskyi** [comment]
> Change looks okay, but we'll only merge this after the next hotfix in line is merged: #12085

@lnardai @doktoric looks like https://github.com/hortonworks/cloudbreak/pull/12085 already merged, so could you please also merge current changes? Thank you.

**Review by lnardai — APPROVED** [review]

**Pull request merged**
