### PR TITLE
CB-16091 Bump CSA versions on 7.2.14 and 7.2.15

### PR DESCRIPTION
**Pull request by ferenc-csaky**

### CODE REVIEW

**Review by lajosrodek — APPROVED** [review]
Approving, but I think the change should be also applied to the [7.2.15.json](https://github.com/hortonworks/cloudbreak/blob/master/template-manager-cmtemplate/src/main/resources/cloudera-manager-template/cdh/7.2.15.json).

**Comment by ferenc-csaky** [comment]
> @ferenc-csaky Is it intentional not to have a tracking Jira ticket for this? (It is missing from both commit title & PR title.)

Great point, I updated the PR. If it LG, can someone merge it pls, I don't have permission. Thanks!

**Review by lacikaaa — CHANGES_REQUESTED** [review]
missing jira ticket

**Comment by ferenc-csaky** [comment]
> missing jira ticket

done

**Comment by lacikaaa** [comment]
> > missing jira ticket
> 
> done

to the commit message please. thats what matters when we check git history. thanks

**Review by pdarvasi — APPROVED** [review]

**Review by lacikaaa — APPROVED** [review]

**Pull request merged**
