### PR TITLE
Ambproxy

### PR DESCRIPTION
**Pull request by keyki**

### CODE REVIEW

**Comment by doktoric** [comment]
@keyki pls check the unit tests

**Comment by keyki** [comment]
Fixed

**Comment by doktoric** [comment]
@keyki https.proxyHost and https.proxyPort can configurable only for both cb and periscope together but useProxyForClusterConnection is configurable separately. Is that make sense or should that be configurable also only together?

**Comment by keyki** [comment]
https.proxyHost and port are jvm standards, could be the same for useProxyForClusterConnection as well, but doesnt really matter since they are running in separate container and have different environment variables

**Pull request merged**
