### PR TITLE
[Hue] - CDPD-32891 - Cloud Break Template change for QP

### PR DESCRIPTION
**Pull request by Amlesh1902**
Already merged the below PR in master branch: https://github.com/hortonworks/cloudbreak/pull/12735

### CODE REVIEW

**Comment by Amlesh1902** [comment]
We introduced a new service "QueryProcessor" in this PR.
Regarding testing, I have doe the testing for the below 8 cases and also got it verified by @lajosrodek.

**AWS:**
- 7.2.15 - Data Engineering for AWS      - RAZ
- 7.2.15 - Data Engineering HA for AWS   - RAZ
- 7.2.15 - Data Engineering for AWS      - Non-RAZ
- 7.2.15 - Data Engineering HA for AWS   - Non-RAZ

**Azure:**
- 7.2.15 - Data Engineering for Azure      - RAZ
- 7.2.15 - Data Engineering HA for Azure   - RAZ
- 7.2.15 - Data Engineering for Azure      - Non-RAZ
- 7.2.15 - Data Engineering HA for Azure   - Non-RAZ

**Comment by horadla23** [comment]
@Amlesh1902 thx! Although I still do not see the urgency here and as I mentioned, only fixes for regressions should come into release branch.
We already have a build for promotion and validation is already started for that build.
cc @foldik @agov

**Comment by Amlesh1902** [comment]
Actually, the main reason is that we are sunsetting the DAS product completely as it is not fully stable and is having so many issues. After R30, we are planning to sunset the DAS from CDW and everywhere.
So currently we are incorporating all the DAS features in Hue along with some optimisation, and hence we create a new service Hue-QueryProcessor.

So, it’s a must go feature for 7.2.15. For that, the CSD changes have already been checked in to the 7.2.15 release, and only the CB changes (this PR) needs to be merged. Until and unless this template changes gets released, the customer have to install the QP service manually which is not good.

So, i checked with the CB team @lajosrodek, and my PR was already approved and it was supposed to land in 2.57. Only there were some issues in rebasing it. However, i was expecting it to get merged in 2.57.

Also as i already mentioned, i already have performed all the 8 cases of testing for both AWS and Azure and got it verified by @lajosrodek

**Comment by lnardai** [comment]
2.57 reached prod.
We'll wait one approve from @hortonworks/cloudbreak-wolf team.
we might include and deploy this if there is a hotfix required for 2.57, but not going to do a release for just the sake of this change.

**Review by lajosrodek — APPROVED** [review]
LGTM

**Comment by lajosrodek** [comment]
@Amlesh1902 I just noticed that this and the former `master` PR only targeted the 7.2.15 blueprints. We since have [7.2.16](https://github.com/hortonworks/cloudbreak/tree/CB-2.57.0/core/src/main/resources/defaults/blueprints/7.2.16) ones as well, so I believe the Hue changes made here shall be also applied there to be consistent. I do not mind having a separate PR for that, up to you. In any case, 7.2.16 is already in `CB-2.57.0` (even though the actual images may not get released to Stage & Prod), so ideally the 7.2.16 changes would have to also land in `CB-2.57.0`.

@horadla23 @lnardai Your opinion is most welcome in that regards. :smile:

**Comment by horadla23** [comment]
Do we still need this? 2.57 is released and 2.58 is created so 2.58 will eventually contain this change.

**Comment by horadla23** [comment]
No response,closing

**Pull request closed without merging**
