### PR TITLE
CB-21529 Update 7.2.17 cluster templates name, description and all re…

### PR DESCRIPTION
**Pull request by vbrodetskyi**
…lated files (according to newly added Schema Registry service).

See detailed description in the commit message.

### CODE REVIEW

**Comment by vbrodetskyi** [comment]
retest this please

**Comment by vbrodetskyi** [comment]
retest this please

**Comment by pkedvessy** [comment]
We are in the middle of introducing 7.2.18 based on 7.2.17. Please wait for https://github.com/hortonworks/cloudbreak/pull/14719 to be merged and then update 7.2.18 templates name and descriptions as well.

**Comment by pkedvessy** [comment]
@vbrodetskyi https://github.com/hortonworks/cloudbreak/pull/14719, please update 7.2.18 templates according to your 7.2.17 changes.

**Pull request closed without merging**
