### PR TITLE
Revert "Revert "CB-20833 Set 7.2.16 as default.""

### PR DESCRIPTION
**Pull request by lnardai**
This reverts commit 8fc5238dc332a01ae28428f3b3f643b3cc5bbd88.

See detailed description in the commit message.

Originally this was reverted due to a regression in the 7.2.16 line, more details here:
https://jira.cloudera.com/browse/OPSAPS-66187

Since its fixed we should have the same 7.2.16 as a default version.

### CODE REVIEW

**Comment by lnardai** [comment]
Need to clear up if latest image in dev catalog contains the fix or not.

**Review by aszegedi — APPROVED** [review]

**Comment by akanto** [comment]
After resolving the conflicts, what is the next step here? Is there any particular reason why this is not merged?

**Comment by lnardai** [comment]
We had a conversation in an internal slack channel where @lacikaaa asked to actually verify the scaling problem. I'll validate the change today or tomorrow and get this merged.

**Comment by lnardai** [comment]
Verified worker group upscale works with 7.2.16. This should be merged.

**Pull request merged**
