### PR TITLE
CB-18157 Expose database related info in Distrox list API

### PR DESCRIPTION
**Pull request by lacikaaa**
For UI related improvement we need to expose DB version and type on the list interface

See detailed description in the commit message.

### CODE REVIEW

**Review by schfeca75 — APPROVED** [review]

**Comment by pdarvasi** [comment]
I would double-check why `externaldatabaseengineversion` it is not filled for any but 29 values on mow-dev, maybe it's a bug, maybe it works as designed, it is weird for sure.

```
select count(*) from stack where externaldatabaseengineversion  is not null;
// 29

select count(*) from stack where externaldatabasecreationtype  is not null;
// 40788

select count(*) from stack;
// 100627
```

**Comment by lacikaaa** [comment]
> I would double-check why `externaldatabaseengineversion` it is not filled for any but 29 values on mow-dev, maybe it's a bug, maybe it works as designed, it is weird for sure.

it's only filled if you specify the version in the request afaik. Otherwise we will go with whatever is on the image, or whatever redbeams bring up

**Comment by pdarvasi** [comment]
> it's only filled if you specify the version in the request afaik. Otherwise we will go with whatever is on the image, or whatever redbeams bring up

If that's the case then it is not that useful because we _always_ have the engine info in Redbeams, and only in special cases here. Don't we want to query the version from Redbeams?

**Comment by lacikaaa** [comment]
we would have to sync db versions from:
- redbeams
- embedded db

to make this useful. but it's not part of this task. we can't fetch db version from redbeams on list API-s, so it has to be stored locally.

**Comment by pdarvasi** [comment]
We could instead

- fetch it when empty
- and save locally

That way, it would be more useful

**Pull request merged**
