### PR TITLE
CB-21550 Remove CDP_GCP entitlement

### PR DESCRIPTION
**Pull request by keyki**
See detailed description in the commit message.

### CODE REVIEW

**Review by lajosrodek — APPROVED** [review]
LGTM

**Comment by doktoric** [comment]
did we already removed on the ui ?

**Comment by lajosrodek** [comment]
Hmm, looks like there is still reference to `CDP_GCP` in https://github.com/hortonworks/hortonworks-cloud/blob/9d280d922c9cbad44dc78be95125c92aca6c01d3/web/cloudbreak-ui/src/app/create-cluster/selectors/global.selectors.spec.ts#L6 .

@tiborm  @zoltanzseli Folks, do you think a follow-up PR is needed?

**Comment by keyki** [comment]
Thank @lajosrodek I checked that, it's a test file.

**Pull request merged**
