### PR TITLE
CB-13052 null pointer check for network validation if network not ava…

### PR DESCRIPTION
**Pull request by doktoric**
…ilable

See detailed description in the commit message.

### CODE REVIEW

**Review by topolyai5 — APPROVED** [review]

**Review by lajosrodek — APPROVED** [review]
LGTM. Just one note: having an UT case for the `null` network would be also helpful.

**Comment by lajosrodek** [comment]
Having deja vu: looks like this potential NPE was already mentioned [here](https://github.com/hortonworks/cloudbreak/pull/10939#discussion_r652951589) 😄

**Comment by lajosrodek** [comment]
Follow-up to #10939

**Comment by doktoric** [comment]
UT is coming with a next PR

**Review by topolyai5 — APPROVED** [review]

**Pull request merged**
