### PR TITLE
Distx 367 gatewaynodes

### PR DESCRIPTION
**Pull request by smaniraju**
Reintroduce gateway nodes in cdp 702 and 710 templates.

Closes #DISTX-367

### CODE REVIEW

**Comment by shwethags** [comment]
@doktoric @akanto can you merge this please and make it part of CB 2.18 on mow dev? Here is the explanation for making this part of both 7.0.2 and 7.1.0:
We reverted the patch in CB 2.17 release, as that release didn’t have any template changes and we would have forced customers to update their cluster definitions
But CB 2.18 has template changes, renaming of templates. This is required for both 7.0.2 and 7.1.0 runtimes and hence require changes to both templates

**Comment by akanto** [comment]
@aszegedi could you take a look and confirm whether this is compatible with our e2e tests, please?

@horadla23 could you take a look and confirm whether this is compatible with our image tests, please?

**Comment by horadla23** [comment]
As far as I can tell this change is compatible with image tests (meaning that image tests can still start), although I cannot tell if distrox clusters can be provisioned successfully with our images and these updated templates (that should be checked with latest e2epromoted builds and with these templates).

**Comment by horadla23** [comment]
Maybe it is worth to describe here how this change/these templates was tested (which environment, using what kind of builds of CM/CDH, using what kind of image , etc.)

**Comment by smaniraju** [comment]
> Maybe it is worth to describe here how this change/these templates were tested (which environment, using what kind of builds of CM/CDH, using what kind of image , etc.)

The following clusters were launched on AWS from local laptop CB (name":"cloudbreak","version":"2.18.0-rc.6-1-gf1c7cfc")  with the PR changes in two new environments and all four datahub clusters were launched successfully.
1. CDP 1.2 - Data Engineering: Apache Spark, Apache Hive, Apache Oozie
    Run1. with 0 gateway nodes
    Run2. with 1 gateway node
```
    Default Prewarmed Images were used.
    Name : CM version
    Version: 7.0.2
    Base Url: http://cloudera-build-us-west-1.vpc.cloudera.com/s3/build/1717199/cm7/7.0.2/redhat7/yum/
    Name: Cloudera Runtime
    Version: 7.0.2-1.cdh7.0.2.p2.1879959
    Parcel URL: http://cloudera-build-us-west-1.vpc.cloudera.com/s3/build/1879959/cdh/7.x/parcels/
```


2. 7.1.0 - Data Engineering: Apache Spark, Apache Hive, Apache Oozie
    Run1. with 0 gateway nodes
    Run2. with 1 gateway node
```
    Default Prewarmed Images were used.
    Name : CM version
    Version: 7.1.0
    Base Url: http://cloudera-build-us-west-1.vpc.cloudera.com/s3/build/1877086/cm7/7.1.0/redhat7/yum/
    Name: Cloudera Runtime
    Version: 7.1.0-1.cdh7.1.0.p0.1885501
    Parcel URL: http://cloudera-build-us-west-1.vpc.cloudera.com/s3/build/1885501/cdh/7.x/parcels/
```

**Comment by horadla23** [comment]
> > Maybe it is worth to describe here how this change/these templates were tested (which environment, using what kind of builds of CM/CDH, using what kind of image , etc.)
> 
> The following clusters were launched on AWS from local laptop CB (name":"cloudbreak","version":"2.18.0-rc.6-1-gf1c7cfc") with the PR changes in two new environments and all four datahub clusters were launched successfully.
> 
> 1. CDP 1.2 - Data Engineering: Apache Spark, Apache Hive, Apache Oozie
>    Run1. with 0 gateway nodes
>    Run2. with 1 gateway node
> 
> ```
>     Default Prewarmed Images were used.
>     Name : CM version
>     Version: 7.0.2
>     Base Url: http://cloudera-build-us-west-1.vpc.cloudera.com/s3/build/1717199/cm7/7.0.2/redhat7/yum/
>     Name: Cloudera Runtime
>     Version: 7.0.2-1.cdh7.0.2.p2.1879959
>     Parcel URL: http://cloudera-build-us-west-1.vpc.cloudera.com/s3/build/1879959/cdh/7.x/parcels/
> ```
> 
> 1. 7.1.0 - Data Engineering: Apache Spark, Apache Hive, Apache Oozie
>    Run1. with 0 gateway nodes
>    Run2. with 1 gateway node
> 
> ```
>     Default Prewarmed Images were used.
>     Name : CM version
>     Version: 7.1.0
>     Base Url: http://cloudera-build-us-west-1.vpc.cloudera.com/s3/build/1877086/cm7/7.1.0/redhat7/yum/
>     Name: Cloudera Runtime
>     Version: 7.1.0-1.cdh7.1.0.p0.1885501
>     Parcel URL: http://cloudera-build-us-west-1.vpc.cloudera.com/s3/build/1885501/cdh/7.x/parcels/
> ```

Ok, it should work with our images

**Comment by shwethags** [comment]
@akanto Can you merge this please?

**Pull request merged**
