### PR TITLE
CDPD-4781 Increase HBase max blocking store files

### PR DESCRIPTION
**Pull request by petersomogyi**
Increase `hbase.hstore.blockingStoreFiles` configuration value to 50 for HBase RegionServers.

### CODE REVIEW

**Comment by joshelser** [comment]
Nice! Looks about right.

Have you tested this out by hand? I can walk you through that if not. Cloudbreak doesn't have automation in place to validate blueprint changes, so we can do them a big favor by making sure it works as expected.

**Comment by petersomogyi** [comment]
I haven't done testing apart from verifying CM uses `hbase_hstore_blockingStoreFiles` for `hbase.hstore.blockingStoreFiles`.

**Comment by petersomogyi** [comment]
**Testing done:**
Added custom cluster template and created Data Hub Clusters based on this template using GBN 1511602.
On the created cluster I checked configuration for `hbase.hstore.blockingStoreFiles` and it is `50`.

**Comment by joshelser** [comment]
@keyki can you or someone on the team please help us get this merged? Peter has done his due-diligence to test this and show it works. Thanks in advance!

**Pull request merged**
