### PR TITLE
CDPSDX-4175 Add "/backups" to both backup & restore location on RAZ r…

### PR DESCRIPTION
**Pull request by grace303303**
…oot dir
JIRA:[CDPSDX-4175](https://jira.cloudera.com/browse/CDPSDX-4175)

ISSUE & SOLUTION: We fixed the upgrade/resize database backup location issue on RAZ root dir using [CB-21778](https://jira.cloudera.com/browse/CB-21778) but we didn't fix that location when resize is doing restore. This PR is fixing that (as well as change the place where we fix that issue for backup so the change is made earlier and would work for both backup and restore).

**BEFORE:** resize restore failed
Screen Shot 2023-06-23 at 12 04 43 PM

**AFTER:** resize backup & restore succeed. upgrade backup works still. (I hardcoded to only keep backup/restore in the flowchain)
Resize backup and restore:
Screen Shot 2023-06-23 at 11 41 48 AM

Upgrade backup:
Screen Shot 2023-06-23 at 11 38 08 AM

### CODE REVIEW

**Comment by grace303303** [comment]
retest this please

**Review by sxxgrc — APPROVED** [review]

**Review by votez — APPROVED** [review]

**Review by lajosrodek — CHANGES_REQUESTED** [review]
Changes look alright, but there are zero tests for these logics. Could you please cover them with some UTs?

**Comment by grace303303** [comment]
> Changes look alright, but there are zero tests for these logics. Could you please cover them with some UTs?

Thank you for checking @lajosrodek ! The unit test was added for the method modifyBackupLocation() in [the previous PR](https://github.com/hortonworks/cloudbreak/pull/14843/files) when we tried to fix it for the backup, and here is the file: https://github.com/hortonworks/cloudbreak/blob/cdfe8879145d4254fc9fb56e9c6a9c63f69229e6/datalake/src/test/java/com/sequenceiq/datalake/service/sdx/dr/SdxBackupRestoreServiceTest.java Please let me know if it's good enough!! Thank you!!

**Comment by lajosrodek** [comment]
@grace303303 We indeed have `SdxBackupRestoreServiceTest`, that is completely fine. On the other hand, it would be also nice to cover the changes of `SdxReactorFlowManager` and `DatalakeBackupActions`. It is also okay if you prefer to do this in a separate PR, in which case please raise a Jira ticket for tracking. :smile:

**Comment by grace303303** [comment]
> @grace303303 We indeed have `SdxBackupRestoreServiceTest`, that is completely fine. On the other hand, it would be also nice to cover the changes of `SdxReactorFlowManager` and `DatalakeBackupActions`. It is also okay if you prefer to do this in a separate PR, in which case please raise a Jira ticket for tracking. 😄

Thanks a lot for the suggestions @lajosrodek ! I added unit tests for `SdxReactorFlowManagerTest.java`. For `DatalakeBackupActions` there are currently no unit tests at all for it and the change I made was a revert of what I added in [CB-21778](https://jira.cloudera.com/browse/CB-21778), so I didn't add unit tests for it. Please let me know if it is ok. Thank you!!

**Review by lajosrodek — APPROVED** [review]
Super, thanks, LGTM

**Review by kkalvagadda1 — APPROVED** [review]

**Pull request merged**
