### PR TITLE
CB-17255 Revert "[oozie] OPSAPS-62127 Remove Oozie NameNode whitelist setting."

### PR DESCRIPTION
**Pull request by arvaiadam**
As it turned out with a multi comp test run our previous cloudbreak commit needs to be reverted.

The commit was added due to a CM change which should handle namenode whitelist for Oozie but as testing pointed out it does not work for cloud buckets.

Reverts hortonworks/cloudbreak#12708

### CODE REVIEW

**Comment by lnardai** [comment]
Rebase and retarget this to master please.

**Comment by lnardai** [comment]
Please also rebase your branch to 2.57.0  (37 commits)

**Comment by lnardai** [comment]
This could be closed in favour of this:
https://github.com/hortonworks/cloudbreak/pull/12809
?

**Comment by arvaiadam** [comment]
yes, thank you @lnardai

**Pull request closed without merging**
