### PR TITLE
CB-12002 adding hbase-spark jars to HBASE_CLASSPATH in opdb blueprint

### PR DESCRIPTION
**Pull request by symat**
This commit is needed to allow any Spark job to connect to an HBase running in Public Cloud. 

Previously this configuration change had to be made manually in CM for HBase, now we make it to be the default config, so any 7.2.10+ HBase cluster created in the cloud will be reachable from Spark through hbase-spark connector.

### CODE REVIEW

**Review by petersomogyi — APPROVED** [review]
Looks good from HBase perspective.

**Comment by doktoric** [comment]
HODOR until CDPD-25051 not implemented

**Comment by symat** [comment]
Hello @doktoric !

after some considerable amount of time, we finally have the necessary symlinks in the 7.2.11 parcel that makes this blueprint change upgrade-friendly.

I tested the new opdb blueprint in the cloud. I provisioned a COD (Operational Database, HBase) cluster with a relatively recently built runtime version (7.2.11.0-150) where the symlinks are all already present. Thanks to the extra config added to the blueprint, now I was able to use the Spark-Hbase connector from a DataEngineering (spark2) cluster, connecting to the COD database. 

The symlinks in the 7.2.11 parcel:

```
[csso_mszalay@cod--1u4tfaib8p9tx-worker1 ~]$ ls -la /opt/cloudera/parcels/CDH/lib/hbase_connectors/lib/hbase-spark.jar
lrwxrwxrwx 1 root root 34 Jun 23 05:36 /opt/cloudera/parcels/CDH/lib/hbase_connectors/lib/hbase-spark.jar -> hbase-spark-1.0.0.7.2.11.0-150.jar

[csso_mszalay@cod--1u4tfaib8p9tx-worker1 ~]$ ls -la /opt/cloudera/parcels/CDH/lib/hbase_connectors/lib/hbase-spark-protocol-shaded.jar
lrwxrwxrwx 1 root root 50 Jun 23 05:36 /opt/cloudera/parcels/CDH/lib/hbase_connectors/lib/hbase-spark-protocol-shaded.jar -> hbase-spark-protocol-shaded-1.0.0.7.2.11.0-150.jar

[csso_mszalay@cod--1u4tfaib8p9tx-worker1 ~]$ ls -la /opt/cloudera/parcels/CDH/lib/hbase_connectors/lib/scala-library.jar
lrwxrwxrwx 1 root root 25 Jun 23 05:36 /opt/cloudera/parcels/CDH/lib/hbase_connectors/lib/scala-library.jar -> scala-library-2.11.12.jar
```

With these extra jars on the classpath, every opdb hbase clusters will be able to handle spark connections without the need of manual tweaking. 

Could you take a look on this change?

**Review by doktoric — APPROVED** [review]

**Comment by symat** [comment]
thanks @doktoric for the review!
I'm not familiar with the process, do I need to do anything more with the PR? 
(I think I can not merge it, at least I see no button on the github UI)

**Comment by symat** [comment]
Hello @doktoric,
could you please merge this PR or let me know who to ask or how to proceed?
Thanks!

**Pull request merged**
