### PR TITLE
CB-10910 Add Cruise Control to the Knox Topology template

### PR DESCRIPTION
**Pull request by benyoka**
Added Cruise Control to the exposed services list and the Knox topology template.

Testing:
- Updated the unit test for ExposedServices
- Tested manually

### CODE REVIEW

**Comment by benyoka** [comment]
retest this please

**Comment by doktoric** [comment]
We need icon on the ui side

**Comment by benyoka** [comment]
Created a separate ticket for the icon.

**Comment by benyoka** [comment]
retest

**Comment by doktoric** [comment]
ExposedServiceCollectorTest unit test failed @benyoka

**Comment by patrik-marton** [comment]
> ExposedServiceCollectorTest unit test failed @benyoka

Looks like there are 5 test cases in ExposedServiceCollectorTest.java where the expected map does not contain CRUISE-CONTROL, but the tested function's return value does.

**Review by doktoric — APPROVED** [review]

**Pull request merged**
