### PR TITLE
CDPSDX-715 - suppress kafka warnings.

### PR DESCRIPTION
**Pull request by jasonwmcswain**
This change will suppress the 3 kafka warnings that were showing up in the datalake, based on the light duty blueprint.

Notes:
* including all 3 blueprint changes, but only tested the lite-duty version.  (HA is not supported in GA, but adding the configs now to avoid technical debt that must be done after GA for 1.1.

Tests performed:   (only "cdp-sdx.bp")
1. deployed cluster in mow-dev, verified via CM API that these 3 configuration values are available in the current supported CM version.
2. deploy via CLI with configuration changes to verify that there were no provision errors when including the 3 values in the blueprint.

Closes #CDPSDX-715

### CODE REVIEW

**Comment by jasonwmcswain** [comment]
Is there anything i need to do to assist in the pull request here?

**Comment by jasonwmcswain** [comment]
verified that all 3 configuration options are available in CM:

Version: Cloudera Enterprise 7.x.0 (#1312036 built by jenkins on 20190730-0355 git: 1ef7869f5dc580724ffbb376211fe15acda70a5a)

**Comment by keyki** [comment]
I merged your other PRs and now it's conflicting. Can you please rebase your PR?

**Comment by jasonwmcswain** [comment]
Hello @keyki, I have rebased the branch.  please review my latest changes.

**Comment by keyki** [comment]
Hm, I'm not sure it is conflicting again :(

**Comment by jasonwmcswain** [comment]
closing pull request b/c this branch is too old and keeps getting merge conflicts.
new PR:  https://github.com/hortonworks/cloudbreak/pull/5971

**Pull request closed without merging**
