### PR TITLE
CB-13198 Remove the built-in operational database template

### PR DESCRIPTION
**Pull request by stoty**
Remove the templates and blueprints for 7.2.14.

See detailed description in the commit message.

### CODE REVIEW

**Comment by stoty** [comment]
Converted to draft, because this depends on ODX-1087 to not break COD completely.

**Review by lajosrodek — CHANGES_REQUESTED** [review]
The removals surely look alright, but I think the following should be also done:
* Update `core/src/main/resources/application.yml` to remove the 7.2.14 `cdp-opdb` entry.
* Update [ClusterTemplateTest.validateDefaultCount()](https://github.com/hortonworks/cloudbreak/blob/5e01c950f04066fe6c4f6045c23a6a4dc74b39bc/integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/ClusterTemplateTest.java#L368) accordingly, so that the correct number of cluster definitions are expected.
* What about 7.2.15 blueprints & cluster definitions? Should not they be also removed?

**Comment by stoty** [comment]
Thank you, I've hopefully addressed the problems in the new version.

However, I get a 404 when trying to access the unit test results from the check.
http://build.eng.hortonworks.com/job/cloudbreak-pull-request-builder-unit-test/15579/

Do you know how to access the results ?

**Review by lajosrodek — APPROVED** [review]
Thanks, LGTM

**Comment by lajosrodek** [comment]
Failure reason is common in all the cases:
```
Execution failed for task ':environment-api:compileJava'.
> Could not resolve all files for configuration ':environment-api:compileClasspath'.
   > Could not find com.cloudera.cdp:cdp-sdk-java:0.9.51.
```
Could you please rebase onto top of `master`? There have been some Gradle dependency fixes that will hopefully make this PR green again. :smile:

**Comment by stoty** [comment]
Thank you, I've rebased it.

**Comment by stoty** [comment]
We've released  COD 1.20 version, so this is unblocked.
Please merge this @lajosrodek.

**Comment by lajosrodek** [comment]
I cannot, someone from Duck will do that (they are the guardian for the current `master` / 2.53).

CC @keyki @pdarvasi

**Pull request merged**
