### PR TITLE
2.69 to 2.70

### PR DESCRIPTION
**Pull request by horadla23**
See detailed description in the commit message.

### CODE REVIEW

**Review by lajosrodek — APPROVED** [review]
LGTM

**Review by biharitomi — APPROVED** [review]

**Review by lajosrodek — CHANGES_REQUESTED** [review]
Wait a sec, the target branch is `master`, which is 2.71.

**Comment by horadla23** [comment]
@lajosrodek correct, fixed

**Review by lajosrodek — APPROVED** [review]
Better now :smile:

**Pull request merged**
