### PR TITLE
CB-10712. Increase timeout for CM client even further to mitigate dep…

### PR DESCRIPTION
**Pull request by oleewere**
…loy client issues

details:
- increase CM client proxy timeout to 4 min
- write/read/connect timeout should be larger than that value, so set those to 245 seconds

See detailed description in the commit message.

### CODE REVIEW

**Review by lacikaaa — APPROVED** [review]

**Review by biharitomi — APPROVED** [review]

**Review by biharitomi — CHANGES_REQUESTED** [review]
The CCM related clients also need to be revised.

**Review by biharitomi — APPROVED** [review]

**Comment by biharitomi** [comment]
I approved the PR, but afaik the timeout needs to be increased in cluster-proxy its self cc: @cegganesh84 
Based on Cluster-Proxy related follow up within: https://jira.cloudera.com/browse/ENGESC-5493

**Comment by doktoric** [comment]
I think the base branch should be 2.36 right ?

**Comment by oleewere** [comment]
@doktoric , not sure, for a use case like that we can recommend this: CB-10725 (see in internal jira)

**Review by pdarvasi — APPROVED** [review]

**Comment by pdarvasi** [comment]
@akanto What's your opinion, should we merge this one?

**Review by bergerdenes — APPROVED** [review]

**Comment by akanto** [comment]
This is an acceptable temporary workaround. It does not solve the real problem, but it increases the timeout over the 3.5 minutes that can be found in CM.

**Pull request merged**
