### PR TITLE
CB-11217 Extracted all platform configs under cdp: namespace. Left th…

### PR DESCRIPTION
**Pull request by lnardai**
…e global supportedPlatforms+experimental platforms and added a separate block for features/platforms configuration. We should be able to clearly see what feature is enabled on what platforms, and this should be decoupled from the fact which platform is enabled at the moment. Default values should only be provided through application.yml configurations, never @Value os PostConstruct annotations.

**Please DO NOT MERGE THIS until we agreed on a format and helm charts are updated properly.**

### CODE REVIEW

**Comment by doktoric** [comment]
This probably requires cloudbreak-deployer updates if we have any pointer there for this properties.

**Comment by lnardai** [comment]
retest this!

**Comment by doktoric** [comment]
retest this please

**Comment by doktoric** [comment]
@lnardai do you plan to finish this?

**Pull request closed without merging**
