### PR TITLE
CB-17045. Configure collector types for node-exporter.

### PR DESCRIPTION
**Pull request by oleewere**
collectors:
- cpu
- cpufreq
- diskstats
- filefd
- filesystem
- loadavg
- meminfo
- netstat
- pressure
- processes
- stat
- systemd
- vmstat
- xfs
see more: https://github.com/prometheus/node_exporter/blob/master/README.md#collectors

### CODE REVIEW

**Review by lnardai — APPROVED** [review]
Looks good, especially with the systemd service list is limited. 
Other collects should have smaller footprints as well right?

**Comment by lnardai** [comment]
conntrack might be also useful, or anything network health related.

**Comment by oleewere** [comment]
> Looks good, especially with the systemd service list is limited. Other collects should have smaller footprints as well right?

could be, but main reason to limit systemd, it's output was huge, and prometheus could not even display all the requested metrics for that for a timestamp, i did not have that problem for other metrics, but later we can filter more unused data out if we will know the models better

**Comment by oleewere** [comment]
> conntrack might be also useful, or anything network health related.

i think /proc/sys/net/netfilter/ was not present anyway, will check again and extend that later in different PR if needed (netstat collector should contain most of that which we should be interested)

**Pull request merged**
