### PR TITLE
ENGESC-17176 Set GCP VM canIpForward to FALSE

### PR DESCRIPTION
**Pull request by bergerdenes**
See detailed description in the commit message.

### CODE REVIEW

**Review by lajosrodek — APPROVED** [review]
LGTM

**Comment by horadla23** [comment]
this should be targeted to 2.63, shouldn't it?

**Comment by bergerdenes** [comment]
> this should be targeted to 2.63, shouldn't it?

At the time I raised this PR it was not decided. If 2.63 will go live in the upcoming day(s) I will close this and open a new one against it. Otherwise, it would be nice to hotfix it. One client is waiting for it.

**Comment by doktoric** [comment]
@horadla23 we will merge it back because in that case we are not depending on the release.

**Pull request merged**
