### PR TITLE
CB-16107 Change the DBStack's resourceCrn type in the entity. We use …

### PR DESCRIPTION
**Pull request by topolyai5**
…the Crn object in the DBStack entity but it unnecessary because we almost everytime parse it before and after to a string

See detailed description in the commit message.

### CODE REVIEW

**Comment by horadla23** [comment]
don't we want to fix all entities in redbeams to avoid String<->Crn conversions in redbeams? cc @gergopapi2

**Review by horadla23 — CHANGES_REQUESTED** [review]
please fix every `dbStack.getResourceCrn().toString()` in the code to remove unnecessary toString() call (examples: `AbstractRedbeamsStartAction`, `AbstractRedbeamsStopAction`, etc.)

**Comment by topolyai5** [comment]
> please fix every `dbStack.getResourceCrn().toString()` in the code to remove unnecessary toString() call (examples: `AbstractRedbeamsStartAction`, `AbstractRedbeamsStopAction`, etc.)

thanks, fixed

**Review by lajosrodek — APPROVED** [review]
LGTM. Note: As I see, `CrnConverter` is also being used for [DatabaseConfig.resourceCrn](https://github.com/hortonworks/cloudbreak/blob/de6326d210282aae17d191c0ff22703325edf278/redbeams/src/main/java/com/sequenceiq/redbeams/domain/DatabaseConfig.java#L42-L44) and [DatabaseServerConfig.resourceCrn](https://github.com/hortonworks/cloudbreak/blob/de6326d210282aae17d191c0ff22703325edf278/redbeams/src/main/java/com/sequenceiq/redbeams/domain/DatabaseServerConfig.java#L49-L51). Would it be beneficial to make similar changes to those properties as well?

**Comment by horadla23** [comment]
> LGTM. Note: As I see, `CrnConverter` is also being used for [DatabaseConfig.resourceCrn](https://github.com/hortonworks/cloudbreak/blob/de6326d210282aae17d191c0ff22703325edf278/redbeams/src/main/java/com/sequenceiq/redbeams/domain/DatabaseConfig.java#L42-L44) and [DatabaseServerConfig.resourceCrn](https://github.com/hortonworks/cloudbreak/blob/de6326d210282aae17d191c0ff22703325edf278/redbeams/src/main/java/com/sequenceiq/redbeams/domain/DatabaseServerConfig.java#L49-L51). Would it be beneficial to make similar changes to those properties as well?

@lajosrodek scroll up:)

**Pull request merged**
