### PR TITLE
CB-20156 Added telemetry to tests using SdxInternalTestDto

### PR DESCRIPTION
**Pull request by szabolcs-horvath**
See detailed description in the commit message.

### CODE REVIEW

**Comment by szabolcs-horvath** [comment]
retest this please

**Comment by lnardai** [comment]
Can we exclude such cases where we only add code the test project? or would it be ok to accept 0%?

**Comment by lnardai** [comment]
retest this please!

**Comment by lnardai** [comment]
Merging this since it's only integration-test code where coverage should not be taken into account.

**Pull request merged**
