### PR TITLE
Fix a bug causing missing m5a, r5a and i3.metal instances

### PR DESCRIPTION
**Pull request by thaibui**
Thai from Bazaarvoice here.

While trying to upgrade our production Cloudbreak from 2.4 to 2.7. I discovered that we don't have all the latest EC2 instances available. Especially the newer but cheaper AMD instances (m5a and r5a). The i3.metal instance is also missing even though we have the i3.x family. There's several small bugs:

* The first was that the JQ .select command was only looking for "Compute Instances", while i3.metal is "Compute Instances (bare metal)" so I added that condition and the i3.metal appears.
* m5a, r5a instances are missing because they appear very recently (Nov 6) in us-east-1 and a couple of other regions, the Python script looks at us-west-1 by default. I changed it to look both us-east/west-1 since AWS always release the new stuff in us-east-1.
* If the number of digits is greater than 3, the AWS json will use a "," (comma) to format them, causing Cloudbreak to unable to load the value as INT. I fixed this in the script to avoid this error especially for really large instance type. For example, 

```
-          "Memory": "3,904",
+          "Memory": 3904
```

I ran the command `make generate-zone-vms` so the change set is big. I can remove them if need be.

### CODE REVIEW

**Comment by sodre90** [comment]
@thaibui Hi, thank you for your contribution. It looks good for me, but can you please rebase your commits to rc-2.7 branch? We would like to have these fixes from 2.7 line.

**Comment by thaibui** [comment]
@sodre90 ah, makes sense. just did it. hopefully this will go out to 2.7.3 soon and I will just perform an upgrade instead of building a custom version. thx!

**Comment by sodre90** [comment]
@thaibui thanks. Anyway you can use your jsons without custom cloudbreak, you only need to copy them into /var/lib/cloudbreak-deployment/etc (or the destination where your cbd deployment is). We mount that directory into cloudbreak container and when cloudbreak try to find these jsons, then it will look that directory first, and won't read the ones from the classpath. So you can update anytime these jsons if there are new instance types from amazon and you want to use them.

**Comment by thaibui** [comment]
@sodre90 makes sense. thanks for the info!

**Pull request merged**
