### PR TITLE
CFM-2480: Fix flow management datahub creation - change core_settings…

### PR DESCRIPTION
**Pull request by taz1988**
… to stub_dfs

See detailed description in the commit message.

### CODE REVIEW

**Review by bergerdenes — CHANGES_REQUESTED** [review]
The config provider is missing for "STUB_DFS" service type.

**Comment by taz1988** [comment]
@bergerdenes I got the information, that that part of the work will be handled in a different ticket: https://jira.cloudera.com/browse/CB-17791

Could you please proceed with code review and merge?

**Comment by bergerdenes** [comment]
In this case, that CB ticket should be resolved first, then this can be merged too.

**Review by bergerdenes — APPROVED** [review]

**Comment by biharitomi** [comment]
@taz1988 This couldn't be merged, since the existence of the STUB_DFS service type depends on the version of the CM itself. The permanent solution would be to let CB configure it automatically based on the CM version.
[The related PR for autoconfig](https://github.com/hortonworks/cloudbreak/pull/13135)

**Comment by taz1988** [comment]
Thanks @biharitomi I will close this one

**Comment by biharitomi** [comment]
@taz1988 Please reopen this one as it is a required fix for 7.2.16 as the original template contains invalid `core_settings` configs. 
Sorry, I was wrong! 
It would be also a more stable way if we let CB add these services automatically based on the CM version but having it in a template that already sticked to the 7.2.16 version is fine.

**Review by biharitomi — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
