### PR TITLE
CB-3573 Remove the opdb custom blueprint from the UI

### PR DESCRIPTION
**Pull request by joshelser**
Per MattS, we only want one shape per cluster and we
expect users to modify the one we provide if they would
make some change to the instance type.

The expectation is that deleting the "OpDB custom" entry from application.yml, it will stop showing up in the "Custom" tab under the "Cluster Template" drop-down.

### CODE REVIEW

**Comment by keyki** [comment]
Hi,  can you please send the PR against 2.13?

**Comment by keyki** [comment]
Also if you want to get rid of the blueprint for existing users also then you need to create an SQL migration script also.

**Comment by joshelser** [comment]
> you need to create an SQL migration script also

Ok. Is there a tool to create the migration (For rails, `rails generate migration`) or just do it by hand?

**Comment by keyki** [comment]
> > you need to create an SQL migration script also
> 
> Ok. Is there a tool to create the migration (For rails, `rails generate migration`) or just do it by hand?

cbd migrate cbdb new "CB-3372 remove CDP 1.0 blueprints and templates" will generate the base template, but you can create it by hand also

**Comment by joshelser** [comment]
Switched the base to rc-2.13 and added the migration.

I wasn't sure if the `name` column is being built from the description in the blueprint or the entry in application.yml -- that's why I made the `LIKE` statement match `%ustom`. In the application.yml, it was "Custom" but in the blueprint description it was "custom".

No associated cluster template for this one. Thanks for the review!

**Comment by joshelser** [comment]
Thanks Krisztian.

**Pull request merged**
