### PR TITLE
[DO NOT MERGE YET] BUG-116401 Automatically enable Knox SSO for all supported services w…

### PR DESCRIPTION
**Pull request by lajosrodek**
…hen possible

### CODE REVIEW

**Comment by akanto** [comment]
By default, CB launches embedded LDAP and I think it will not work with the SSO cases since embedded LDAP will not be connected to Ranger, Atlas, Ambari etc. 

So this pull request will not work, except if you have an external LDAP attached to the cluster.

**Comment by keyki** [comment]
Since this PR will not work for the majority of the cases should we close this?

**Comment by lajosrodek** [comment]
@sidseth What's your opinion, does it make sense to keep this approach given the feedback of Attila & Krisztian above?

**Comment by sidseth** [comment]
This will likely need a relook anyway with DistroX, and potentially Altus cluster shapes coming in. If I understand correctly, the default CB deployed LDAP needs to be special cased to not enable SSO?
I suspect we're going to ask component teams to support Knox trusted proxy - which doesn't actually mean they'll actually support it. Enabling SSO was a mechanism to make sure the UIs are accessible correctly. That bit will still need to be solved.

**Comment by lajosrodek** [comment]
@sidseth Good point. The problem is indeed with the default-deployed demo LDAP server that is otherwise not wired with any distro component but Knox. I am not sure if CB could be enhanced to do this extra work (i.e. treat the demo LDAP just like an external one, configuring it for all components etc., except that it has to be explicitly installed as an extra step when bringing up Knox). Closing this PR for now as the approach should probably be rethought/revisited later.

**Pull request closed without merging**
