### PR TITLE
CB-17166: Use new entitlement added for Azure LB

### PR DESCRIPTION
**Pull request by kkalvagadda1**
Use the new entitlement "CDP_DATA_LAKE_LOAD_BALANCER_AZURE" added to enable load balancer for Azure environments.

Currently, the same entitlement is used for both Azure and GCP load balancers. Having the separation would allow us to get them to GA separately.

### CODE REVIEW

**Comment by horadla23** [comment]
Is entitlement present in thunderhead code?

**Comment by kkalvagadda1** [comment]
> Is entitlement present in thunderhead code?

yes. I'm also working on getting promoted to PROD as well so that we don't get into a situation where this change goes to PROD without thunderhead changes.

**Review by yg-gd — APPROVED** [review]

**Comment by lnardai** [comment]
Please fix IT.

**Comment by lnardai** [comment]
Is this really a must have for 2.57? Could you retarged it to master?

**Comment by kkalvagadda1** [comment]
> Is this really a must have for 2.57? Could you retarged it to master?

I addressed the tests. This is a trivial change and would enable us to GA to Load balancers for Azure.

**Comment by lnardai** [comment]
We are not holding back the release for this. If there is a hotfix for a more pressing issue, we can include this since it's small scope low risk change.

**Review by lnardai — APPROVED** [review]

**Pull request merged**
