### PR TITLE
CDPCP-4714. Add DEACTIVATE_USER entitlement

### PR DESCRIPTION
**Pull request by handavid**
This commit adds the DEACTIVATE_USER entitlement in preparation for
use by user sync. The mock usermanagement service was also modified
to return the DEACTIVATE_USER entitlement in the getAccount response.

### CODE REVIEW

**Comment by lacikaaa** [comment]
shall we `CDP` or `FMS` prefix for this entitlement? Something like `CDP_USERSYNC_DEACTIVATE_USER` is a bit more meaningful for me

**Comment by handavid** [comment]
> shall we `CDP` or `FMS` prefix for this entitlement? Something like `CDP_USERSYNC_DEACTIVATE_USER` is a bit more meaningful for me

The entitlement itself is already in the UMS and covers the "disable user" feature as a whole, not just the user sync portion. I could rename the properties in the MockUserManagementService and application.yml to match the entitlement, removing the "user.sync" portions.

**Comment by lacikaaa** [comment]
not necessary, in that case just please resolve the conflicts, otherwise LGTM. thanks

**Comment by handavid** [comment]
@lacikaaa rebased and resolved the conflicts. thanks!

**Review by lacikaaa — APPROVED** [review]

**Pull request merged**
