### PR TITLE
Merge 2.31 to master

### PR DESCRIPTION
**Pull request by gergopapi2**
See detailed description in the commit message.

### CODE REVIEW

**Review by sodre90 — APPROVED** [review]

**Review by aszegedi — APPROVED** [review]

**Comment by LinaAtAustin** [comment]
@gergopapi2 My code change in "CB-9055" is already in master branch. https://github.com/hortonworks/cloudbreak/commit/b1f5b8a9ccb2c2b8b7e78c99fa52d640917faade. I committed the change to master branch, and then to 2.31.0 branch. I am not sure why you need to merge my change back to master branch.

If you rebase on master, will you be able to pick up my change and you don't have to merge my change to master branch again?

What is the process to commit code change? 
1) developer commits to master, then commits to other branches OR
2) developer commits to other release branches, then another person commits multiple commits to master?

**Comment by gergopapi2** [comment]
> @gergopapi2 My code change in "CB-9055" is already in master branch. [b1f5b8a](https://github.com/hortonworks/cloudbreak/commit/b1f5b8a9ccb2c2b8b7e78c99fa52d640917faade). I committed the change to master branch, and then to 2.31.0 branch. I am not sure why you need to merge my change back to master branch.
> 
> If you rebase on master, will you be able to pick up my change and you don't have to merge my change to master branch again?
> 
> What is the process to commit code change?
> 
> 1. developer commits to master, then commits to other branches OR
> 2. developer commits to other release branches, then another person commits multiple commits to master?

@LinaAtAustin Its actually rather 2.: you commit something to a release branch and then merge it up to master (i.e. if you had a commit to 2.29, then you merge all the way through 2.30, 2.31 to master). Currently the developer doing the commit to a release branch is responsible to do the merge as soon as possible.

**Review by topolyai5 — APPROVED** [review]

**Comment by keyki** [comment]
> @gergopapi2 My code change in "CB-9055" is already in master branch. [b1f5b8a](https://github.com/hortonworks/cloudbreak/commit/b1f5b8a9ccb2c2b8b7e78c99fa52d640917faade). I committed the change to master branch, and then to 2.31.0 branch. I am not sure why you need to merge my change back to master branch.
> 
> If you rebase on master, will you be able to pick up my change and you don't have to merge my change to master branch again?
> 
> What is the process to commit code change?
> 
> 1. developer commits to master, then commits to other branches OR
> 2. developer commits to other release branches, then another person commits multiple commits to master?

Git merge will get the commit from 2.31 as the commit ID is different. The content is the same so it will not cause any problems.

**Comment by horadla23** [comment]
updated merge pr: https://github.com/hortonworks/cloudbreak/pull/9149

**Pull request closed without merging**
