### PR TITLE
CB-6164 Remove entitlement check for CCM

### PR DESCRIPTION
**Pull request by lacikaaa**

### CODE REVIEW

**Comment by lacikaaa** [comment]
please wait for UI change

**Comment by doktoric** [comment]
@lacikaaa  I think we should check how the local dev will work. I guess in local you should use ccm = false right ?

**Comment by keyki** [comment]
This will just enable the option. It does not set it true by default.

**Comment by lacikaaa** [comment]
@doktoric the default will be `DIRECT`, that won't change

**Pull request merged**
