### PR TITLE
CB-3080 : Set CapacityScheduler as default scheduler for YARN in the …

### PR DESCRIPTION
**Pull request by ashutoshc**
…Data Engineering blueprint (addendum-2)

**DELETE THIS TEMPLATE BEFORE SUBMITTING**

Describe the change you are making here!

Please include tests. Check out these examples:

- https://github.com/hortonworks/cloudbreak/blob/master/core/src/test/java/com/sequenceiq/cloudbreak/service/blueprint/BlueprintLoaderServiceTest.java#L62-L76

Please include a short description. Check out these examples:

- https://github.com/hortonworks/cloudbreak/commit/888b2e2a8887def28a24e26efcd6d9ca5863733a

If your PR resolves any open issue(s), please indicate them like this so they will be closed when your PR is merged:

Closes #xxx
Closes #xxx

### CODE REVIEW

**Comment by sunilgovind** [comment]
This change looks good
@daszabo  pls help to review and merge

**Comment by sunilgovind** [comment]
@RamVenkatesh We have verified this one line change in a cluster shared by Namit

**Comment by sunilgovind** [comment]
Thank you, Pinging Santosh now.

**Comment by keyki** [comment]
What is exactly the change here? I see 2 space characters added.

**Comment by sunilgovind** [comment]
Yes. The change is 2 spaces on acl side.

**Comment by sunilgovind** [comment]
@RamVenkatesh  @keyki @miklosgergely 
Santhosh helped to get a cluster from this template. Config is fine in that. Thanks

**Comment by keyki** [comment]
I'm traveling now, but once I get to my destination and jenkins built the PR I'll deploy to dev.

**Pull request merged**
