### PR TITLE
CB-12546 Added Flink GCP templates

### PR DESCRIPTION
**Pull request by ferenc-csaky**

### CODE REVIEW

**Comment by doktoric** [comment]
@ferenc-csaky thanks. One small thing, can you please squash together the commits?

**Comment by ferenc-csaky** [comment]
@doktoric I squashed the commits, although there is a "Squash and Merge" option on the UI, which does the same, is it disabled for this repo?

**Comment by doktoric** [comment]
retest this please

**Comment by ferenc-csaky** [comment]
retest

**Pull request merged**
