### PR TITLE
CB-21757 adding the me-central-1 ssl certificate to aws certificates.

### PR DESCRIPTION
**Pull request by doktoric**
See detailed description in the commit message.

### CODE REVIEW

**Review by lacikaaa — APPROVED** [review]

**Comment by lajosrodek** [comment]
For reference, here are the cert details:

```
        Issuer: C = US, O = "Amazon Web Services, Inc.", OU = Amazon RDS, ST = WA, CN = Amazon RDS me-central-1 Root CA RSA2048 G1, L = Seattle
        Validity
            Not Before: May  6 23:20:09 2022 GMT
            Not After : May  7 00:20:09 2062 GMT
        Subject: C = US, O = "Amazon Web Services, Inc.", OU = Amazon RDS, ST = WA, CN = Amazon RDS me-central-1 Root CA RSA2048 G1, L = Seattle
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                RSA Public-Key: (2048 bit)
```

**Comment by lajosrodek** [comment]
Available certs from AWS CLI:

```
aws --region me-central-1 rds describe-certificates

{
    "Certificates": [
        {
            "CertificateIdentifier": "rds-ca-ecc384-g1",
            "CertificateType": "CA",
            "Thumbprint": "6cb23d56510932d28946d0858ce48c90c9824b26",
            "ValidFrom": "2022-05-07T00:44:37+00:00",
            "ValidTill": "2122-05-07T01:44:37+00:00",
            "CertificateArn": "arn:aws:rds:me-central-1::cert:rds-ca-ecc384-g1",
            "CustomerOverride": false
        },
        {
            "CertificateIdentifier": "rds-ca-rsa4096-g1",
            "CertificateType": "CA",
            "Thumbprint": "2bff95bb0a23e110856800c37de14abc208fec39",
            "ValidFrom": "2022-05-07T00:40:23+00:00",
            "ValidTill": "2122-05-07T01:40:23+00:00",
            "CertificateArn": "arn:aws:rds:me-central-1::cert:rds-ca-rsa4096-g1",
            "CustomerOverride": false
        },
        {
            "CertificateIdentifier": "rds-ca-rsa2048-g1",
            "CertificateType": "CA",
            "Thumbprint": "2f0c13891565299af97b930bc722da849504c028",
            "ValidFrom": "2022-05-06T23:20:09+00:00",
            "ValidTill": "2062-05-07T00:20:09+00:00",
            "CertificateArn": "arn:aws:rds:me-central-1::cert:rds-ca-rsa2048-g1",
            "CustomerOverride": false
        }
    ]
}
```

**Review by lajosrodek — CHANGES_REQUESTED** [review]

**Review by lajosrodek — APPROVED** [review]
Thanks, LGTM

**Comment by doktoric** [comment]
retest this please

**Pull request merged**
