### PR TITLE
CB-10160 - Increase socket timeout and update maxFailoverAttempts=0 for NiFi service

### PR DESCRIPTION
**Pull request by moresandeep**
**Describe the change you are making here!**
NiFi team ran into issues with a customer with large uploads. This issue is identified as a critical fix and needs to land as quick as possible (hotfix).

The changes proposed in this PR are:
- increase the socket timeout for Nifi
- set retry and failover counts to zero 

**Testing**
The patch was tested on a cluster running NiFi

### CODE REVIEW

**Comment by keyki** [comment]
@moresandeep by hotfix what do you mean? The master branch will be 2.35 which will land on prod by 15th of Dec. Is that good enough or they need it earlier?

**Comment by moresandeep** [comment]
> @moresandeep by hotfix what do you mean? The master branch will be 2.35 which will land on prod by 15th of Dec. Is that good enough or they need it earlier?

Sorry for the delay in responding, we have a customer that we needs this fix asap from what I have been told.
This is some background

- https://jira.cloudera.com/browse/CDPD-20187?focusedCommentId=4184689&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-4184689

- https://jira.cloudera.com/browse/CDPD-20187?focusedCommentId=4184720&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-4184720

**Comment by keyki** [comment]
Can they change the topology manually to fix it until the fix is deployed? 2.34 is scheduled for Monday and if we want this asap then we will need to hotfix 2.34 next week. In that case this change should go to CB-2.34.0 branch.

**Comment by moresandeep** [comment]
They can change it manually but were asking for an urgent hotfix (and I don't know about how they work so apologies)
Let me ask them and I'll reply here.

**Comment by moresandeep** [comment]
While we are waiting for that, I think we can still go ahead with merging this in master, what do you think @keyki?

**Review by keyki — APPROVED** [review]

**Comment by moresandeep** [comment]
Thank you @keyki!

**Pull request merged**
