### PR TITLE
CB-1433. Remove hard-coded password from SDX template

### PR DESCRIPTION
**Pull request by adoroszlai**
## What changes were proposed in this pull request?

Use master password in SDX template instead of hard-coded one.

## How was this patch tested?

Adjusted unit test.  Still have to test actual cluster deployment.

### CODE REVIEW

**Comment by akanto** [comment]
Please check that the general.password strength is acceptable for Ranger, if it is week, then please change the pattern for the general password.

**Comment by akanto** [comment]
Looks good. I guess we need UI change as well, right?

**Comment by adoroszlai** [comment]
> guess we need UI change as well

Not really, as it already requires these properties (min 8. chars, at least 1 letter and 1 number).

**Comment by adoroszlai** [comment]
Integration test fails with:

```
swagger-validation_1  | The swagger spec at "http://cloudbreak:8080/cb/api/swagger.json" is invalid against swagger specification 2.0. see errors :
swagger-validation_1  | - definitions.ClusterV4Request.password in body has invalid pattern: "(?=.*[0-9])(?=.*[a-zA-Z]).*"
```

The pattern works fine both in Java and in the [Swagger Editor](https://editor.swagger.io/).

The problem is that this validation is performed by `go-swagger`, and Go's `regexp` doesn't support lookaheads: https://github.com/go-swagger/go-swagger/issues/917

**Pull request merged**
