### PR TITLE
Revert "[Hue] - CDPD-32891 - Cloud Break Template change for QP"

### PR DESCRIPTION
**Pull request by lajosrodek**
This reverts commit 81fe343ceb9b6de36c65504a7c75154dd84ca6ff / #12611.

### CODE REVIEW

**Comment by lajosrodek** [comment]
CC @Amlesh1902 have to revert this due to [CDPD-39355](https://jira.cloudera.com/browse/CDPD-39355).

**Comment by lajosrodek** [comment]
swagger-compatibility-test failures:
```
================ COMPATIBILITY BREAKS in datalake ================
ERROR rules:
	[REQ-E002] Removed Enum value from Request contract: #/paths//dbconfig/connectionparams/get/parameters/1 (documentation: https://swagger-spec-compatibility.readthedocs.io/en/latest/rules/REQ-E002.html)
/usr/lib/python3.8/site-packages/swagger_spec_validator/validator20.py:49: SwaggerValidationWarning: Found "$ref: #/definitions/Images" with siblings that will be overwritten. See https://stackoverflow.com/a/48114924 for more information. (path #/definitions/CloudbreakImageCatalogV3/properties/images)
  warnings.warn(
/usr/lib/python3.8/site-packages/swagger_spec_validator/validator20.py:49: SwaggerValidationWarning: Found "$ref: #/definitions/ImageStackDetails" with siblings that will be overwritten. See https://stackoverflow.com/a/48114924 for more information. (path #/definitions/CloudbreakImageCatalogV3/properties/images/properties/base-images/items/properties/stack-details)
  warnings.warn(
/usr/lib/python3.8/site-packages/swagger_spec_validator/validator20.py:49: SwaggerValidationWarning: Found "$ref: #/definitions/StackRepoDetails" with siblings that will be overwritten. See https://stackoverflow.com/a/48114924 for more information. (path #/definitions/CloudbreakImageCatalogV3/properties/images/properties/base-images/items/properties/stack-details/properties/repo)
  warnings.warn(
/usr/lib/python3.8/site-packages/swagger_spec_validator/validator20.py:49: SwaggerValidationWarning: Found "$ref: #/definitions/Versions" with siblings that will be overwritten. See https://stackoverflow.com/a/48114924 for more information. (path #/definitions/CloudbreakImageCatalogV3/properties/versions)
  warnings.warn(
===============================================================================

================ COMPATIBILITY BREAKS in cloudbreak ================
/usr/lib/python3.8/site-packages/swagger_spec_validator/validator20.py:49: SwaggerValidationWarning: Found "$ref: #/definitions/Images" with siblings that will be overwritten. See https://stackoverflow.com/a/48114924 for more information. (path #/definitions/CloudbreakImageCatalogV3/properties/images)
  warnings.warn(
/usr/lib/python3.8/site-packages/swagger_spec_validator/validator20.py:49: SwaggerValidationWarning: Found "$ref: #/definitions/ImageStackDetails" with siblings that will be overwritten. See https://stackoverflow.com/a/48114924 for more information. (path #/definitions/CloudbreakImageCatalogV3/properties/images/properties/base-images/items/properties/stack-details)
  warnings.warn(
/usr/lib/python3.8/site-packages/swagger_spec_validator/validator20.py:49: SwaggerValidationWarning: Found "$ref: #/definitions/StackRepoDetails" with siblings that will be overwritten. See https://stackoverflow.com/a/48114924 for more information. (path #/definitions/CloudbreakImageCatalogV3/properties/images/properties/base-images/items/properties/stack-details/properties/repo)
  warnings.warn(
/usr/lib/python3.8/site-packages/swagger_spec_validator/validator20.py:49: SwaggerValidationWarning: Found "$ref: #/definitions/Versions" with siblings that will be overwritten. See https://stackoverflow.com/a/48114924 for more information. (path #/definitions/CloudbreakImageCatalogV3/properties/versions)
  warnings.warn(
ERROR rules:
	[REQ-E002] Removed Enum value from Request contract: #/paths//v4/dbconfig/connectionparams/get/parameters/1 (documentation: https://swagger-spec-compatibility.readthedocs.io/en/latest/rules/REQ-E002.html)
===============================================================================
```
These are due to the `com.sequenceiq.cloudbreak.api.endpoint.v4.database.base.DatabaseType` revert; they appear in [DatabaseConfigEndpoint](https://github.com/hortonworks/cloudbreak/blob/246cb30c7c970f75a48b34d46c55e7d20c4284de/datalake-api/src/main/java/com/sequenceiq/sdx/api/endpoint/DatabaseConfigEndpoint.java#L31) and [DatabaseConfigV4Endpoint](https://github.com/hortonworks/cloudbreak/blob/246cb30c7c970f75a48b34d46c55e7d20c4284de/core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/database/DatabaseConfigV4Endpoint.java#L29).

**Review by bergerdenes — APPROVED** [review]

**Review by lnardai — APPROVED** [review]

**Comment by lnardai** [comment]
if you wish, I can press force merge on this PR. Let me know if you need it, since @doktoric is not available.

**Comment by lnardai** [comment]
Merging it with special request from @hortonworks/cloudbreak-wolf team.
See @lajosrodek explanation.

**Pull request merged**
