### PR TITLE
CB-10784: Fixed missing freeipa pillar

### PR DESCRIPTION
**Pull request by TheTinkerDad**
See detailed description in the commit message.

### CODE REVIEW

**Review by lacikaaa — APPROVED** [review]

**Review by keyki — APPROVED** [review]

**Comment by TheTinkerDad** [comment]
retest

**Comment by TheTinkerDad** [comment]
retest this please

**Comment by TheTinkerDad** [comment]
retest this please

**Comment by TheTinkerDad** [comment]
retest this please

**Pull request merged**
