### PR TITLE
[CDPD-5755] Add default DE Hue HA template to support Customer request

### PR DESCRIPTION
**Pull request by weixiaxu**
Add Hue HA template for DE template to support customer's new request

Closes #CDPD-5755

### CODE REVIEW

**Comment by weixiaxu** [comment]
recheck

**Comment by weixiaxu** [comment]
@keyki  Can you please help review and let me know where should I update the template name to avoid "No cluster template found with name 'CDP 1.2 - Data Engineering Hue HA template: Apache Spark, Apache Hive, Hue, Apache Oozie"? Thanks

**Comment by keyki** [comment]
> @keyki Can you please help review and let me know where should I update the template name to avoid "No cluster template found with name 'CDP 1.2 - Data Engineering Hue HA template: Apache Spark, Apache Hive, Hue, Apache Oozie"? Thanks

In your template you referenced the blueprint incorrectly instead of the name what you have specified in the application.yml
```
CDP 1.2 - Data Engineering Hue HA template: Apache Spark, Apache Hive, Hue, Apache Oozie
CDP 1.2 - Data Engineering Hue HA: Apache Spark, Apache Hive, Hue, Apache Oozie
```
 This is why tests were failing. I fixed this naming and push to your branch.

**Comment by keyki** [comment]
Probably the same template will be needed for Azure as well, right?

**Comment by keyki** [comment]
I'll verify this PR manually as we don't have automated to tests these kind of PRs. For Azure you'll have to create a similar template (there are examples for it). Mostly you'll have to a pick an instance type.

**Comment by keyki** [comment]
I have launched a Data Hub with this template and it seems like everything is up and running. Beyond that I cannot really validate if functionality wise is correct or not.

**Pull request merged**
