### PR TITLE
Remved hard coded os type

### PR DESCRIPTION
**Pull request by abhishekaypurohit**
Small PR to remove hardcoded os type for an image. 

`BUILD SUCCESSFUL in 7m 48s
361 actionable tasks: 71 executed, 290 up-to-date`

@keyki @handavid @lacikaaa

### CODE REVIEW

**Comment by keyki** [comment]
Can you please include a JIRA to your commit? Later it makes it easy to track back certain items. No need to create a new item just use on of the FreeIpa item which you think it the most related.

**Comment by abhishekaypurohit** [comment]
Here is the JIRA : https://jira.cloudera.com/browse/DISTX-135

**Comment by keyki** [comment]
Hi, 

I mean the commit message should have a jira like `DISTX-135 Remved hard coded os type`

**Comment by keyki** [comment]
@abhishekaypurohit can you please use the following patter for your commit messages `CB-1034 Shared Data context support in Cloudbreak` JIRA-ID message

**Comment by sodre90** [comment]
Can you please add JIRA ID to the commit messages and instead of merging your own commits please wait until one of the other team member merge your issue. Thanks

**Pull request merged**
