### PR TITLE
Merge2520

### PR DESCRIPTION
**Pull request by doktoric**
See detailed description in the commit message.

### CODE REVIEW

**Comment by yg-gd** [comment]
Needs to include [a02214e](https://github.com/hortonworks/cloudbreak/pull/12303/commits/a02214e1de9b2c072a7f07b5fb9028f6c68b6d98)

**Comment by horadla23** [comment]
> Needs to include [a02214e](https://github.com/hortonworks/cloudbreak/pull/12303/commits/a02214e1de9b2c072a7f07b5fb9028f6c68b6d98) or merge #12303

that commit is not on 2.52 branch. merge PRs (merging commits from feature branch forward) should contain only commits present on the feature branch

**Comment by horadla23** [comment]
i missed that https://github.com/hortonworks/cloudbreak/pull/12303/commits/a02214e1de9b2c072a7f07b5fb9028f6c68b6d98 contains the fix for compile error

**Comment by lacikaaa** [comment]
out of date

**Pull request closed without merging**
