### PR TITLE
CB-16095: Wrong http for Solr service port in Knox topology.

### PR DESCRIPTION
**Pull request by kkalvagadda1**
Fixed the exposed service JSON file

HTTP port on which Solr service listens is different from Knox configuration as a result, requests to Solr service that hit Knox GW are routed to 8983 but the actual service is listening on 8993 resulting in a connection failure error.

TESTING:
Made sure that Knox topology configuration is updated to 8993 when the datalake is set up to use HTTP.

### CODE REVIEW

**Comment by hreeve-cloudera** [comment]
Can we get some more information on what was wrong and what testing was done in the commit message? So we don't lose that context.

**Comment by kkalvagadda1** [comment]
> Can we get some more information on what was wrong and what testing was done in the commit message? So we don't lose that context.

Updated the PR description.

**Comment by hreeve-cloudera** [comment]
> > Can we get some more information on what was wrong and what testing was done in the commit message? So we don't lose that context.
> 
> Updated the PR description.

Are you also going to add those changes to the commit message next time you do an update? Just want to make sure they're easily accessible after this is merged in.

**Review by gezan — APPROVED** [review]

**Comment by lacikaaa** [comment]
@kkalvagadda1 could you add pr description to the commit message?

**Comment by kkalvagadda1** [comment]
> @kkalvagadda1 could you add pr description to the commit message?

Done.

**Review by pdarvasi — APPROVED** [review]

**Pull request merged**
