### PR TITLE
Switch to alpine

### PR DESCRIPTION
**Pull request by akanto**
See detailed description in the commit message.

### CODE REVIEW

**Comment by bergerdenes** [comment]
A few files missed:
- integration-test/docker-compose_template.yml
- integration-test/scripts/check-results.sh
- integration-test/scripts/docker-build.sh

**Review by bergerdenes — CHANGES_REQUESTED** [review]
missed some files

**Comment by akanto** [comment]
thanks, it looks like that these image definitions are scattered through the entire project...

**Comment by lnardai** [comment]
Please reopen if needed again.

**Comment by akanto** [comment]
Oh, sorry this was an abandoned pull request, and the change went in under a different pull request. We don't need this.

**Comment by lajosrodek** [comment]
For reference, see #12078. Alpine could not be used, RedHat UBI was picked instead.

**Comment by akanto** [comment]
For reference, which has just been reverted to debian: https://github.com/hortonworks/cloudbreak/pull/12405

**Pull request closed without merging**
