### PR TITLE
RMP-11186 - add new HDF Messaging blueprint that includes Kafka, and …

### PR DESCRIPTION
**Pull request by YolandaMDavis**
…Schema Registry

The new blueprint requires that an external database be available for installation. RDS database should be prepared as per documentation before deployment.

**For MySQL** 

JDBC Driver for testing: https://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-java-5.1.42.tar.gz

prepping db:
https://docs.hortonworks.com/HDPDocuments/HDF3/HDF-3.2.0/installing-hdf/content/configuring_sam_and_schema_registry_metadata_stores_in_mysql.html

**For Postgres** 

prepping db:
https://docs.hortonworks.com/HDPDocuments/HDF3/HDF-3.2.0/installing-hdf/content/configure_postgres_to_allow_remote_connections.html 

Once database is prepped and registered cluster can be deployed with blueprint using the advanced settings to attach external database.  On the Services group in the blueprint ports 7788 and 7789 can be exposed to ensure access to Schema Registry from the browser.

### CODE REVIEW

**Comment by dbialek2** [comment]
@YolandaMDavis One question: When registering the database as a "Database Configuration" which type should I use, per blueprint? Should I select "Other"? And then can I just name it anything?
related doc: https://docs.hortonworks.com/HDPDocuments/Cloudbreak/Cloudbreak-2.7.2/content/external-db/index.html#example-2-other-type

**Comment by jtstorck** [comment]
+1
I tested this PR using MySQL (which MUST use the JDBC driver that Yolanda referenced, it doesn't work with ConnectorJ 8, even though the page says it'll work with MySQL 5.5-5.7 and 8).

Yolanda is addressing an issue with Postgres, but this test was successful with attaching an AWS MySQL RDS instance.

**Comment by YolandaMDavis** [comment]
@dbialek2 there is a new External DB type called Registry which needs to be used.

**Comment by YolandaMDavis** [comment]
@doktoric not quite clear on what failed above?  Details seemed to indicate failure to upload test results (not a failed test).

**Pull request merged**
