### PR TITLE
Merge 2.9 to 2.10

### PR DESCRIPTION
**Pull request by Bajzathd**
See detailed description in the commit message.

### CODE REVIEW

**Comment by lacikaaa** [comment]
@Bajzathd do we still need this PR? it has failing tests but no activity

**Comment by Bajzathd** [comment]
I opened it when I saw 2.10 is behind 2.9, but it did not see much activity since then. So it is okay for me to close this and open a new one when needed for a feature or release.

**Comment by doktoric** [comment]
do we still need this @Bajzathd ?

**Comment by Bajzathd** [comment]
Closed it

**Pull request closed without merging**
