### PR TITLE
CB-2047. Update CM and CDH versions

### PR DESCRIPTION
**Pull request by adoroszlai**
Also append CM build number to the version displayed in CB UI.

### CODE REVIEW

**Comment by keyki** [comment]
Have you tested it with kerberized SDX and DistroX?

**Comment by keyki** [comment]
I tested the below builds
```
    "cm": {
      "repository": {
        "baseUrl": "http://cloudera-build-us-west-1.vpc.cloudera.com/s3/build/1214979/cm7/7.x.0/redhat7/yum/",
        "version": "7.x.0"
      },
      "products": [
        {
          "name": "CDH",
          "version": "7.0.0-1.cdh7.0.0.p0.1214471",
          "parcel": "http://cloudera-build-us-west-1.vpc.cloudera.com/s3/build/1214471/cdh/7.x/parcels/"
        }
      ]
    },
```
we can merge the PR if you want, one change is the CM version is `7.x.0` I don't think we need to put it as `7.x.0-1214979`

**Comment by adoroszlai** [comment]
I added the build number to CM version so that it gets displayed in the _Cluster Information_ section of the UI.  I think this helps with tickets where people report some error happened with CM version "7.x.0" and you have to dig for the specific version in logs.  It doesn't cause any problems during deployment (been using this "style" for a while).

**Comment by keyki** [comment]
Okay, we can merge if you want.

**Comment by adoroszlai** [comment]
Thanks!

**Pull request merged**
