### PR TITLE
CB-9217 Ability to deploy multiple Raz instances on DH cluster. We ad…

### PR DESCRIPTION
**Pull request by doktoric**
…ding RAZ to hostgroups which has ZK master if the cluster contains at least 2 ZK server and also adding to the GW group.

See detailed description in the commit message.

### CODE REVIEW

**Review by cegganesh84 — APPROVED** [review]
I like the check for the ZK group for deciding on RAZ HA.

**Review by sidseth — APPROVED** [review]
Looks good. Not sure the >=3 ZK check is really required (The alternate is to say - install RAZ if ZK is present, and RAZ potentially has at least 2 instances on all clusters - or at least on clusters where CM runs on a separate node)

**Comment by doktoric** [comment]
> Looks good. Not sure the >=3 ZK check is really required (The alternate is to say - install RAZ if ZK is present, and RAZ potentially has at least 2 instances on all clusters - or at least on clusters where CM runs on a separate node)

@sidseth should we then modify the jira comment ? 2 is enough ?

**Comment by sidseth** [comment]
> > Looks good. Not sure the >=3 ZK check is really required (The alternate is to say - install RAZ if ZK is present, and RAZ potentially has at least 2 instances on all clusters - or at least on clusters where CM runs on a separate node)
> 
> @sidseth should we then modify the jira comment ? 2 is enough ?

I think this works reasonably well also, so continue to be +1. RAZ goes HA on shapes which are likely to be HA (multiple ZKs)

**Review by sidseth — APPROVED** [review]

**Pull request merged**
