### PR TITLE
CB-13443: Enabled Load balancing using Knox for Profiler Manager Service.

### PR DESCRIPTION
**Pull request by subrat-mishra**
Profiler Manager Services has 3 main services i.e. profiler_manager_service, profiler_metrics_service and data_discovery_service. They all supports active-active HA now. 
Added enableLoadBalancing explicitly for all the services which would help in scaling. 

Tested these configs on my local cluster.

### CODE REVIEW

**Comment by moresandeep** [comment]
@subrat-mishra the sticky session flag is `false` i am assuming this is because the services are stateless. Other than confirming that the services are stateless everything looks good.

**Review by moresandeep — APPROVED** [review]

**Comment by subrat-mishra** [comment]
> @subrat-mishra the sticky session flag is `false` i am assuming this is because the services are stateless. Other than confirming that the services are stateless everything looks good.

Yes @moresandeep all the services are stateless.

**Review by kumariitr — APPROVED** [review]

**Comment by doktoric** [comment]
@subrat-mishra  is this change backward compatible? We are using this knox configuration for older runtimes as well like 7.2.8? Will it work ?

**Comment by subrat-mishra** [comment]
> @subrat-mishra is this change backward compatible? We are using this knox configuration for older runtimes as well like 7.2.8? Will it work ?

@doktoric I haven't tested on the older runtimes. CB-9745 has similar changes for other services like RANGER, SOLR etc.
@moresandeep can you please let us know the knox configs are backward compatible?

**Comment by moresandeep** [comment]
@doktoric these changes are backwards compatible with 7.2.8.

**Comment by subrat-mishra** [comment]
Thanks @moresandeep for confirming.
@doktoric could you please merge this PR?

**Comment by doktoric** [comment]
@moresandeep we still support older runtimes then 7.2.8

**Comment by moresandeep** [comment]
I see what you mean, i don't think they will cause any issue for older runtimes but it would be best if we can test it out. 
@subrat-mishra this should be easy to test on an older cluster <7.1.7

**Comment by subrat-mishra** [comment]
@moresandeep, I have tested runtime version 7.1.0 on public cloud. I have manually added the knox configs to the
/var/lib/knox/gateway/conf/topologies/cdp-proxy.xml and verified its working fine. Although the enableLoadBalancing feature was not working which is expected.

**Review by doktoric — APPROVED** [review]

**Pull request merged**
