### PR TITLE
CB-7898: Add SRM to Streaming DataHub cluster templates

### PR DESCRIPTION
**Pull request by Jugis**
See detailed description in the commit message.

### CODE REVIEW

**Comment by doktoric** [comment]
we still need the sql for rename

**Comment by benyoka** [comment]
- Updated GCP and Ycloud templates
- Made application.yml consistent
- Tested updgrade / downgrade manually impacts on db: 
  - on upgrade CB creates new blueprints and marks old blueprints as DEFAULT_DELETED
  - on downgrade CB marks new blueprints as DEFAULT_DELETED and reinstates old blueprints
  - no DB migration script is needed therefore
- added unit test

**Comment by benyoka** [comment]
retest

**Comment by benyoka** [comment]
retest this please

**Comment by benyoka** [comment]
retest this please

**Comment by benyoka** [comment]
retest this please

**Pull request merged**
