### PR TITLE
CB-12301 Support different Flink port in exposed services according to CDH version

### PR DESCRIPTION
**Pull request by ferenc-csaky**

### CODE REVIEW

**Comment by doktoric** [comment]
@ferenc-csaky was it changed or it was never correcT?

**Comment by ferenc-csaky** [comment]
> @ferenc-csaky was it changed or it was never correcT?

It was changed, because 8082 can interfere with other services in some situations.

**Comment by doktoric** [comment]
@ferenc-csaky from which version. How we can handle backward compatibility in this case ?

**Review by doktoric — APPROVED** [review]

**Comment by doktoric** [comment]
retest this please

**Pull request merged**
