### PR TITLE
CB-15942 We fetch the entire environment but we get only a specific v…

### PR DESCRIPTION
**Pull request by topolyai5**
…alue during the auth. It causes an N+1 query.

See detailed description in the commit message.

### CODE REVIEW

**Review by bergerdenes — APPROVED** [review]

**Comment by topolyai5** [comment]
retest this please

**Comment by horadla23** [comment]
we have EnvironmentView, why don't we use it?

**Comment by topolyai5** [comment]
> we have EnvironmentView, why don't we use it?

Instead of long or String value? Or where should I use the EnvironmentView in this PR?

**Comment by horadla23** [comment]
I just thought you can use the view to not fetch the entire environment (I thought that's the goal of this change) with existing code. If you prefer to write another query for this, I'm not against it.

**Review by horadla23 — APPROVED** [review]

**Comment by topolyai5** [comment]
> I just thought you can use the view to not fetch the entire environment (I thought that's the goal of this change) with existing code. If you prefer to write another query for this, I'm not against it.

As I saw in the code the EnvironmentView difference is only that it is not fetching the secrets and fetch reference's view objects only. However, I want to check whether the DB load is decreasing or not if we fetch the specific field instead of an entire object even if that entity is a view.

**Comment by horadla23** [comment]
> > I just thought you can use the view to not fetch the entire environment (I thought that's the goal of this change) with existing code. If you prefer to write another query for this, I'm not against it.
> 
> As I saw in the code the EnvironmentView difference is only that it is not fetching the secrets and fetch reference's view objects only. However, I want to check whether the DB load is decreasing or not if we fetch the specific field instead of an entire object even if that entity is a view.

ok, it makes sense

**Pull request merged**
