### PR TITLE
Optimize cluster telemetry cleanup on termination.

### PR DESCRIPTION
**Pull request by oleewere**
See detailed description in the commit message.

### CODE REVIEW

**Review by biharitomi — APPROVED** [review]

**Comment by bergerdenes** [comment]
should it go to 2.45 as well?

**Comment by oleewere** [comment]
> should it go to 2.45 as well?

i do not think so it's that critical, i think it's fine on master

**Comment by doktoric** [comment]
@oleewere how about with 2.46? do we fine with master?

**Comment by oleewere** [comment]
> @oleewere how about with 2.46? do we fine with master?

same is true there, point of this change to remove unnecessary transaction (also api call happening inside that) - i do not think any 2.46 tests failed on this - so master should be fine

**Pull request merged**
