### PR TITLE
CB-14353 disable direct CM UI debug path in NGiNX configuration.

### PR DESCRIPTION
**Pull request by biharitomi**
See detailed description in the commit message.

### CODE REVIEW

**Comment by lacikaaa** [comment]
can we do it by moving those parts into separate files and use include directive, so we could comment only that line out? I don't like seeing half of the file commented

**Comment by biharitomi** [comment]
I don't think it's worth to move it and have a test environment and cluster to test that refactor.
On the other hand the conditional rewrite logic needs to be there to have evaluated before the location section.

So if you don't like it this way I can remove the entire part and if somebody would like to use this backdoor then needs to look up for it in a previous line of CB. 
cc: @akanto @keyki @doktoric what do you think?

**Review by moresandeep — APPROVED** [review]
I tested the patch in a test cluster and I don't see any 502 or 404s anymore :)

**Comment by akanto** [comment]
I also don't think that refactoring is worth the effort, please go ahead and delete the commented-out lines completely.

**Pull request merged**
