### PR TITLE
CB-12962 set-endpoint-access-gateway fails on existing Medium duty environment

### PR DESCRIPTION
**Pull request by hreeve-cloudera**
When populating the instance metadata for the stack, include the metadata for all gateway instances
instead of only the primary gateway metadata. This will allow the set-endpoint-access-gateway
functionality to be run on stack with multiple gateway isstance, e.g. medium duty data lakes.

Tested by calling the set-endpoint-access-gateway API on a medium duty environment.

### CODE REVIEW

**Comment by horadla23** [comment]
which API is "set-endpoint-access-gateway API"?

**Comment by hreeve-cloudera** [comment]
> which API is "set-endpoint-access-gateway API"?

This is the EnvironmentEndpoint.updateEnvironmentLoadBalancersByName API.

**Comment by horadla23** [comment]
and have you tested it locally (i guess yes)? I just want to make sure that the test covers this change, since it seems we need to allows cert generation in config (`gateway.cert.generation.enabled`)

**Comment by hreeve-cloudera** [comment]
> and have you tested it locally (i guess yes)? I just want to make sure that the test covers this change, since it seems we need to allow cert generation in config (`gateway.cert.generation.enabled`)

Yep. I created a medium duty data lake in my local CB services, and then invoked that API using a curl call. My local dev setup is configured to use the mow-dev PEM service for DNS registration and to generated certs, so I did have "gateway.cert.generation.enabled" set to true and the path to renew the certs was hit.

**Comment by horadla23** [comment]
> > and have you tested it locally (i guess yes)? I just want to make sure that the test covers this change, since it seems we need to allow cert generation in config (`gateway.cert.generation.enabled`)
> 
> Yep. I created a medium duty data lake in my local CB services, and then invoked that API using a curl call. My local dev setup is configured to use the mow-dev PEM service for DNS registration and to generated certs, so I did have "gateway.cert.generation.enabled" set to true and the path to renew the certs was hit.

cool, that's what I wanted to ask, if you used mow-dev PEM. in this case that test should cover the change

**Review by horadla23 — APPROVED** [review]
LGTM

**Comment by horadla23** [comment]
@hreeve-cloudera pls do not forget to create a merge PR to master or ask @pkedvessy to do that since he has a recent change committed into 2.44 too

**Pull request merged**
