### PR TITLE
CB-16162 Streaming blueprints: generate auto-TSL config for SRM Gateway

### PR DESCRIPTION
**Pull request by benyoka**
Streaming template include SRM Gateway role config group so that auto-TLS is generated for the GATEWAY role.

Tested: manual cluster installation

### CODE REVIEW

**Comment by benyoka** [comment]
retest this please

**Review by urbandan — APPROVED** [review]
thanks Bence, LGTM

**Comment by benyoka** [comment]
retest this please

**Review by lajosrodek — APPROVED** [review]

**Comment by lajosrodek** [comment]
@benyoka Two notes:

- Please rebase onto latest `master`; it will likely fix the `swagger-compatibility-test` failure.
- Is it intentional to only make this change to the 7.2.15 blueprints?

**Comment by benyoka** [comment]
retest this please

**Comment by benyoka** [comment]
> @benyoka Two notes:
> 
> * Please rebase onto latest `master`; it will likely fix the `swagger-compatibility-test` failure.

Thanks, let me do that.

> * Is it intentional to only make this change to the 7.2.15 blueprints?

Should I do it retroactively?

**Comment by aszegedi** [comment]
retest this please

**Comment by benyoka** [comment]
retest this please

**Pull request merged**
