### PR TITLE
Have fluentd pick-up autossh logs

### PR DESCRIPTION
**Pull request by chi42**
Add config change to have fluentd pick-up autossh logs from /var/log/autossh-*.log.

### CODE REVIEW

**Comment by oleewere** [comment]
is this needed for 2.14 release? then this can go into rc-2.14 branch instead of master (then we will merge this to master from there)

**Comment by chi42** [comment]
> is this needed for 2.14 release? then this can go into rc-2.14 branch instead of master (then we will merge this to master from there)

@jadair-cloudera  do you know? I'm not familiar with cloudbreak's release schedule

**Comment by oleewere** [comment]
@chi42 2.14 is the next release (October?). the release will happen based on rc-2.14 branch. if it goes only into master, that will be included in 2.15 release

**Comment by chi42** [comment]
Ah I see. Then yes, 2.14 release. thanks @oleewere

**Comment by oleewere** [comment]
@chi42 , can you send this patch against rc-2.14 branch (cherry-pick this for rc-2.14 branch)

**Pull request closed without merging**
