### PR TITLE
CB-11121: Fix FreeIPA HA repair

### PR DESCRIPTION
**Pull request by jamisonbennett**
Fix FreeIPA HA repair. It was missing the new flow which was added to
the provisioning for for configuring the orchestrator. This was added
to the repair's upscale flow.

This was tested manually using a local deployment of cloudbreak.

See detailed description in the commit message.

### CODE REVIEW

**Comment by jamisonbennett** [comment]
I am going to see about getting approval for the 2.38 branch as this regression was introduced into 2.38. I also want to know how this wasn't caught by the e2e test but the repair e2e test passed `TestResult name=testCreateStopStartRepairFreeIpaWithTwoInstances status=SUCCESS`.

**Review by christmasferret — APPROVED** [review]
LGTM

**Review by orngejaket — APPROVED** [review]

**Comment by hreeve-cloudera** [comment]
> I am going to see about getting approval for the 2.38 branch as this regression was introduced into 2.38. I also want to know how this wasn't caught by the e2e test but the repair e2e test passed `TestResult name=testCreateStopStartRepairFreeIpaWithTwoInstances status=SUCCESS`.

If this wasn't caught by the e2e test, how was it caught?

**Comment by jamisonbennett** [comment]
@hreeve-cloudera there are tests that @jasonwmcswain runs and he found it.

**Comment by hreeve-cloudera** [comment]
I'm okay with merging this in as-is. I'm assuming the tests are being investigated?

**Review by hreeve-cloudera — APPROVED** [review]

**Review by lacikaaa — APPROVED** [review]

**Pull request merged**
