### PR TITLE
CB-4774. Fluentd process in master node of DL/DW is leaking memory

### PR DESCRIPTION
**Pull request by oleewere**
- added auto-upgrade script from master branch (just a small change to include auzrestorage_gen2 plugin)
- add new azurestorage gen2 plugin

tested manually

### CODE REVIEW

**Comment by oleewere** [comment]
retest this please

**Comment by oleewere** [comment]
retest this please

**Comment by pdarvasi** [comment]
@oleewere  pls. check the integration test.

**Comment by oleewere** [comment]
@pdarvasi , it's passed once already today

**Pull request merged**
