### PR TITLE
CB-16131: Added proper error handling to SdxEventsService

### PR DESCRIPTION
**Pull request by sxxgrc**
Jira: https://jira.cloudera.com/browse/CB-16131

This specifically serves to introduce actual error throwing for the SdxEventsService. Before we were just returning an empty list and not logging or throwing anything.

This issue is of particular importance due to a difficult experience had during the release of 2.52.0, more info here: https://jira.cloudera.com/browse/CB-15944.

I have simply opted to throw exceptions in the various places where the errors can occur, allowing for them to be received and interpreted.

### CODE REVIEW

**Review by horadla23 — COMMENTED** [review]
LGTM, let's wait for https://github.com/hortonworks/cloudbreak/pull/12351 to be merged then real-ums-test should be executed against this branch too with the label

**Review by yg-gd — APPROVED** [review]

**Comment by sxxgrc** [comment]
Marking this as blocked to wait for #12351.

**Comment by aszegedi** [comment]
retest this please

**Comment by sxxgrc** [comment]
@aszegedi what do you mean? Like re-run the checks or is there something you see wrong with my tests themselves?

**Comment by sxxgrc** [comment]
> `retest this please` is a magic sentence for github to rerun PR check jobs

Ah haha, I wasn't aware of that, that's kinda cool. Thank you.

**Comment by aszegedi** [comment]
Yep! This mean: I'd just like to rerun the PR checks (that's all and no worries ;) ). I made some changes at our Jenkins PR jobs. Unfortunately the `jenkins: cb-integration-test` check was created then removed too soon by me. So this has been stuck at pending state. The PR can be approved and merge even if the `jenkins: cb-integration-test` check is pending, because of this check is not a required one.
In case of new PRs in the future this check won't appear in the list.

**Comment by horadla23** [comment]
please rebase this onto top of master

**Comment by horadla23** [comment]
root cause of ums test failure: this should be called with internal actor too: https://github.com/hortonworks/cloudbreak/blob/b72e5977a9c6d0c47ebb9b098a06256d465ae348/datalake/src/main/java/com/sequenceiq/datalake/service/SdxEventsService.java#L142
like here:
https://github.com/hortonworks/cloudbreak/blob/b72e5977a9c6d0c47ebb9b098a06256d465ae348/datalake/src/main/java/com/sequenceiq/datalake/service/SdxEventsService.java#L131
since errors are not hidden anymore, it appeared

**Review by horadla23 — APPROVED** [review]
LGTM

**Pull request merged**
