### PR TITLE
DISTX-367 Reintroduce gateway nodes in cdp 702 and 710 templates.

### PR DESCRIPTION
**Pull request by smaniraju**
Reintroduce gateway nodes in cdp 702 and 710 templates.

Closes #DISTX-367

### CODE REVIEW

**Comment by akanto** [comment]
Do we need it for 7.02?

**Comment by smaniraju** [comment]
> Do we need it for 7.02?

Based on the comments from @shwetha shivalingamurthy, it has been added for 7.0.2 since even 7.0.2 templates are renamed in 2.18.0 and any 7.0.2 custom definitions needs to be updated.

**Comment by smaniraju** [comment]
The existing 7.1.0 aws and azure templates like aws-dataengineering-710.json, aws-dataengineering-hueha-710, azure-dataengineering-710.json already has gateway hostgroups defined, so the same is not updated in this PR.

**Comment by smaniraju** [comment]
Closing this PR because of merge conflicts will rebase the commit.

**Comment by smaniraju** [comment]
Continued in https://github.com/hortonworks/cloudbreak/pull/7304.

**Pull request closed without merging**
