### PR TITLE
CB-18493 add Readme section about importing mock-infrastructure cert to your trust store and why/when it is needed

### PR DESCRIPTION
**Pull request by biharitomi**
See detailed description in the commit message.

### CODE REVIEW

**Comment by akanto** [comment]
Isn't it duplicated with: https://github.com/hortonworks/cloudbreak/pull/14118 ?

**Comment by biharitomi** [comment]
> Isn't it duplicated with: #14118 ?
Thanks @akanto 
Yes, it look like, but this  has more details and more example. Should I remove the other one?
I think we can keep both to increase the chance of findings in this topic :smile:

**Comment by akanto** [comment]
We can keep this. The other pull request mentions the error symptom as well, so it might be worth moving that one over here.

**Comment by biharitomi** [comment]
> We can keep this. The other pull request mentions the error symptom as well, so it might be worth moving that one over here.

This also has mentioned it, but moved missing part from the #14118 here. cc: @aszegedi

**Review by aszegedi — APPROVED** [review]

**Pull request merged**
