### PR TITLE
Disable Scheduler Configuration Mutation Api

### PR DESCRIPTION
**Pull request by PrabhuJoseph**
Disable Scheduler Configuration Mutation Api. Have tested with launching a CM cluster using CloudBreak and the config is added properly in Safety Valve.

### CODE REVIEW

**Comment by sunilgovind** [comment]
CB-3958

**Comment by keyki** [comment]
As I read through the jira comments this should be enabled as TP feature as not many people is confident making this change to 1.2. If it's still the case then we should not merge this change.

**Comment by keyki** [comment]
It seems like there was an issue when we removed CDP 1.1 templates so that is why IT is failing on this PR. Can you please rebase the branch to be on top of master?

**Comment by sunilgovind** [comment]
recheck

**Pull request closed without merging**
