### PR TITLE
CFM-1486 NiFi Registry in DataHub should use the database provider fo…

### PR DESCRIPTION
**Pull request by vbrodetskyi**
…r flow persistence

See detailed description in the commit message.

### CODE REVIEW

**Review by bbende — APPROVED** [review]
+1

**Review by lajosrodek — APPROVED** [review]
LGTM, approving on behalf of @doktoric who is on vacation.

**Comment by vbrodetskyi** [comment]
@lajosrodek could you please merge changes, because i don't have permissions?

**Comment by lajosrodek** [comment]
@vbrodetskyi sure, I was just waiting for the swagger check to pass. Merged.

**Pull request merged**
