### PR TITLE
CB-12879-1: Add tests around GcpEnvironmentNetworkConverter

### PR DESCRIPTION
**Pull request by brycederriso**
Related to [CB-12979](https://jira.cloudera.com/browse/CB-12879).

I'm touching code in the parent class, `EnvironmentBaseNetworkConverter.java` and want to add regression tests to make sure I don't break anything.

### CODE REVIEW

**Comment by brycederriso** [comment]
retest this please

**Comment by hreeve-cloudera** [comment]
If I understand correctly, the goal of this PR is to get the tests in place before your changes, so that we'll be able to detect any regression problems your next set of changes potentially cause?

**Comment by brycederriso** [comment]
> If I understand correctly, the goal of this PR is to get the tests in place before your changes, so that we'll be able to detect any regression problems your next set of changes potentially cause?

Yes! It also establishes the test classes which I'll then add on to for the main changes in CB-12879.

**Comment by hreeve-cloudera** [comment]
> > If I understand correctly, the goal of this PR is to get the tests in place before your changes, so that we'll be able to detect any regression problems your next set of changes potentially cause?
> 
> Yes! It also establishes the test classes which I'll then add on to for the main changes in CB-12879.

What a great proactive change :). Thanks for doing it!

**Review by hreeve-cloudera — APPROVED** [review]

**Pull request merged**
