### PR TITLE
ENGESC-15134 add X-Forwarded-For to nginx config

### PR DESCRIPTION
**Pull request by sodre90**
See detailed description in the commit message.

### CODE REVIEW

**Review by biharitomi — APPROVED** [review]

**Comment by moresandeep** [comment]
Thank you @biharitomi ! can we make the changes in `location ~ .*/` block? location rules are picked up when request goes to Knox. `clouderamanager` rules is a backdoor access CM.

**Review by moresandeep — CHANGES_REQUESTED** [review]
Can we add this change in the `location ~ .*/` block?

**Comment by sodre90** [comment]
@moresandeep thanks, I missed it

**Review by moresandeep — APPROVED** [review]
Looks good!

**Comment by moresandeep** [comment]
@sodre90 Awesome! thank you so much for your help!

**Review by pdarvasi — APPROVED** [review]

**Comment by pdarvasi** [comment]
@sodre90 I would think about rebasing this to 2.59 as the promotion ticket is already opened for it: https://jira.cloudera.com/browse/SREOPS-7917

**Comment by sodre90** [comment]
@pdarvasi done, edited to 2.59

**Pull request merged**
