### PR TITLE
CB-15159. Improve error handling for stop/start in terms of the Flows

### PR DESCRIPTION
**Pull request by sidseth**
and State Machine.
- Introduces several new states, transitions which are used to process
  failures from different steps.
- State machine for stop/start modified with failureEvents and
  failureStates to make use of these additional states.
- Fix a bug with the existing failure_handled_state not being used, and
  the default Failure state sending out an incorrect event.
- Change various Handlers to make use of events, instead of throwing
  Exceptions.

See detailed description in the commit message.

### CODE REVIEW

**Comment by sidseth** [comment]
Note: The PR is created against CB-14929. That is mainly for the review. Eventually, this will be switched over to be against master once the CB-14929 branch is merged.
Also, this change does not actually change the state of instances on failure. It makes sure the state machine works correctly in case of failures, and wires it up for potential future improvements for CB-15132.

**Comment by lnardai** [comment]
1. integration test jobs are missing, but since it a feature branch I can let that go.
2. No endpoint change, so swagger can be ignored as well

**Comment by lnardai** [comment]
LGTM!

**Review by lnardai — APPROVED** [review]

**Comment by sidseth** [comment]
Thanks for the review. Merging into CB-14929.

**Pull request merged**
