### PR TITLE
DWX-945. Allow anonymous LDAP access to group membership

### PR DESCRIPTION
**Pull request by toddlipcon**
This changes the IPA setup to allow anonoymous (non-bound) LDAP clients
to get group membership. This is slightly more open, security-wise, but
we already expose the list of users, so exposing the list of groups
isn't much worse.

Longer term the solution is provide a read-only LDAP "bind" credential
(CB-2488) but this should unblock DWX in the short term.

### CODE REVIEW

**Comment by toddlipcon** [comment]
I tested this command manually by copy-pasting it into a running environment, but not sure how to test that it works in the salt freeIPA setup context.

Also not sure if there is a better way to run this via salt so that it would get applied to already-launched IPAs (is that possible?)

If someone from the CB team could make sure this is safe before merging that would be great. This is critical to fix DWX-945 which is on the hot list.

**Comment by jamisonbennett** [comment]
There isn't currently a way to update existing FreeIPA servers. Although salt supports it, cloudbreak doesn't do this. It is my understanding that this may be possible in the future when we have HA support, but as of a few weeks ago when I made a similar change to the salt config there was no way to perform and update.

**Comment by toddlipcon** [comment]
I think given DWX pulled in https://github.infra.cloudera.com/CDH/dwx/pull/483/ this one isn't needed as urgently. They switched to using admin credentials to bind, which while not preferable, means this shouldn't be required yet.

We should still merge it, but perhaps into master instead of 2.12? Or alternatively we can set up a proper bind account with the appropriate privileges.

**Comment by acmurthy** [comment]
Ok, let's track this or a better approach for master i.e. September drop. Thanks @toddlipcon!

**Comment by lacikaaa** [comment]
also this kind of change should be applied through rest API in `FreeIpaPostInstallService`

**Comment by keyki** [comment]
Closing the PR until we come to a conclusion to prevent accidental merge.

**Pull request closed without merging**
