### PR TITLE
CB-7646 Use image catalog to determin the stack matrix - instead of using the app config

### PR DESCRIPTION
**Pull request by pkedvessy**
CB-7646 Use image catalog to determin the stack matrix - instead of using the app config. This way the stack matrix will be inline with the image catalog without manually update the app config.

### CODE REVIEW

**Comment by pkedvessy** [comment]
retest this please

**Comment by pkedvessy** [comment]
retest this please

**Comment by pkedvessy** [comment]
retest this please

**Comment by pkedvessy** [comment]
Do not merge this PR before https://github.com/hortonworks/hortonworks-cloud/pull/2274 gets merged

**Comment by agov** [comment]
@pkedvessy The UI part is now merged to master.

**Pull request merged**
