### PR TITLE
CB-17310 Postgres upgrade framework - add the upgrade flow skeleton t…

### PR DESCRIPTION
**Pull request by gergopapi2**
…o redbeams

A new flow skeleton is introduced with the major steps needed to upgrade the postgres server.
The flow steps may not be enough for all providers (e.g. Azure), it can then be extended.
Handlers are stubs. For one handler the SPI is also called.

See detailed description in the commit message.

### CODE REVIEW

**Comment by gergopapi2** [comment]
This commit was already merged to master, but since it breaks the swagger, it needs to be merged to the prod as well.

**Comment by horadla23** [comment]
would it makes sense to open PR only with the breaking API change part? in that case new master code would not reach release branch

**Comment by gergopapi2** [comment]
> would it makes sense to open PR only with the breaking API change part? in that case new master code would not reach release branch
@horadla23 @lacikaaa 
The tests for master ran, there were two azure failures, not related to this commit. Do you still insist to port only the API part to 2.59, or are we good to merge the whole PR to 2.59, as is?

**Comment by horadla23** [comment]
@gergopapi2 instead of checking tests, you could have created the PR with only the API change. but if you are confident, that this won't cause any issue, I am fine with it. Still you need an admin to merge this, I can only approve.

**Pull request closed without merging**
