### PR TITLE
CB-21355 Fix ECDSA requirement check to allow key type if package is not present.

### PR DESCRIPTION
**Pull request by foldik**
See detailed description in the commit message.

### CODE REVIEW

**Review by lnardai — APPROVED** [review]

**Comment by keyki** [comment]
master is 2.71, is this the correct branch?

**Comment by lnardai** [comment]
Yes, it would be beneficial to have this in 2.70 as that's the version on gov-int and testers will complain there.

**Review by lajosrodek — APPROVED** [review]
LGTM

**Comment by lnardai** [comment]
retest this please!

**Review by biharitomi — APPROVED** [review]

**Comment by lnardai** [comment]
```
[0K[1m  Test [22mtestEncryptionWhenNoEbsInfoShouldReturnFalse()[32m PASSED[31m (2.2s)[m

The message received from the daemon indicates that the daemon has disappeared.
Build request sent: Build{id=fad8ab58-9cc4-464f-b97f-9e9d62d50b96, currentDir=/grid/0/jenkins/workspace/workspace/cloudbreak-pull-request-builder-unit-test}
Attempting to read last messages from the daemon log...

> Task :cloud-gcp:test

[0K[1mcom.sequenceiq.cloudbreak.cloud.gcp.setup.GcpBucketRegisterServiceTest[m
```

**Pull request merged**
