### PR TITLE
CDPD-34515: SDX/DataLake compaction configs update

### PR DESCRIPTION
**Pull request by simhadri-g**
CDPD-34041: Standardise compaction configuration across all form factors

### CODE REVIEW

**Comment by horadla23** [comment]
there is no description about this in details here or in the jira, so please add it

**Review by horadla23 — COMMENTED** [review]
there is no description about this in details here or in the jira, so please add it

**Comment by simhadri-g** [comment]
I have updated CDPD-34041 with more details about the patch. Please have a look, Thanks!

**Comment by horadla23** [comment]
> I have updated CDPD-34041 with more details about the patch. Please have a look, Thanks!

thx!

**Review by horadla23 — APPROVED** [review]

**Comment by simhadri-g** [comment]
Thanks, could you please review   https://github.com/hortonworks/cloudbreak/pull/12826 as well. 

Both are related to the same jira.

**Comment by simhadri-g** [comment]
Thanks!

**Pull request merged**
