### PR TITLE
CB-16282 Extend datalake API with instance type

### PR DESCRIPTION
**Pull request by horadla23**
See detailed description in the commit message.

### CODE REVIEW

**Comment by horadla23** [comment]
retest this please

**Comment by horadla23** [comment]
retest this please

**Comment by aszegedi** [comment]
retest this please

**Comment by horadla23** [comment]
TODO: new type instead of map

**Review by lturcsanyi — APPROVED** [review]

**Comment by lturcsanyi** [comment]
Please add instance group name

**Review by lturcsanyi — APPROVED** [review]

**Pull request merged**
