### PR TITLE
CB-15985 Set default runtime to 7.2.14

### PR DESCRIPTION
**Pull request by pkedvessy**
See detailed description in the commit message.

### CODE REVIEW

**Comment by akanto** [comment]
Is this enough? Or shall we change all tests to 7.2.14 as it is described here: https://cloudera.atlassian.net/wiki/spaces/ENG/pages/596149312/How+to+introduce+a+new+Cloudera+Runtime+version#2.-Changing-the-default-Cloudera-Runtime-after-RE-has-branched-it

**Comment by pkedvessy** [comment]
:facepalm: why do we have so many different config properties with the same value!? thanks @akanto for calling out my fault on missing changes and thanks @TheTinkerDad for implementing them. I think we should review that do we really need all of these configs and are they set or not with the expected value when running E2E tests. My latest update was we are calling mow-dev for the default runtime and e2e tests are simply using it without any magic overrides.

**Comment by pkedvessy** [comment]
@TheTinkerDad 's commit is cherry-picked to master: https://github.com/hortonworks/cloudbreak/pull/12221/commits/e3dd828164467d81351059155530ecc8d83fa143

**Review by lnardai — APPROVED** [review]

**Comment by pkedvessy** [comment]
retest this please

**Comment by pkedvessy** [comment]
retest this please

**Pull request closed without merging**
