### PR TITLE
ENGESC-10456 Fix gen credential script to handle freeipa repair

### PR DESCRIPTION
**Pull request by lacikaaa**
See detailed description in the commit message.

### CODE REVIEW

**Comment by hreeve-cloudera** [comment]
I checked out the new ipa commands, and it all looks good to me. Thanks for jumping on this so quickly!

**Review by jamisonbennett — APPROVED** [review]

**Review by hreeve-cloudera — CHANGES_REQUESTED** [review]
@lacikaaa I was taking another look at the gen_credentials_ipa.sh script, and I realized this isn't a complete solution. This add lgoic to explicitly define the server in the `ipa-getkeytab --principal=$PRINCIPAL --keytab=$KEYTAB_PATH` command. However, there are multiple `ipa` commands that occur earlier in the script where we're not specifying the server to connect to. I think if there are multiple FreeIPA instances, then we could run into trouble if the `ipa` commands pick different servers to talk to. So we either need to specify the server explicitly in all `ipa` commands, or update the `/etc/ipa/default.conf` file after a FreeIPA repair to a valid server so the `ipa` commands aren't randomly picking on each time.

I've opened CB-14212 to describe the problem in detail, and I've included the steps where I think this fix would be insufficient. Take a look and let me know if it makes sense.

**Comment by jamisonbennett** [comment]
I agree with @hreeve-cloudera

**Comment by lacikaaa** [comment]
right, thanks @hreeve-cloudera , I'm going to update the `default.conf` and see how it works. In the meanwhile I'll close this

**Pull request closed without merging**
