### PR TITLE
BUG-96700 show details when a long running job fails multiple times

### PR DESCRIPTION
**Pull request by lacikaaa**

### CODE REVIEW

**Comment by keyki** [comment]
Should this go to 2.4?

**Comment by doktoric** [comment]
+1 for 2.4

**Comment by akanto** [comment]
I think the original fix for BUG-96700 was committed to 2.4, I think it makes sense to merge this into 2.4

**Comment by lacikaaa** [comment]
I will put it on 2.4 tomorrow

**Pull request closed without merging**
