### PR TITLE
CB-16174 Drop operational database template for versions before 7.2.10

### PR DESCRIPTION
**Pull request by stoty**
See detailed description in the commit message.

### CODE REVIEW

**Review by lajosrodek — CHANGES_REQUESTED** [review]
Looks okay, but there are two test failures:
* `com.sequenceiq.cloudbreak.service.OpdbServiceEndpointCollectorTest.testPrepareClusterExposedServices()` apparently depends on `defaults/blueprints/7.2.0/cdp-opdb.bp`:
```
java.lang.RuntimeException: java.io.FileNotFoundException: class path resource [defaults/blueprints/7.2.0/cdp-opdb.bp] cannot be opened because it does not exist
	at com.sequenceiq.cloudbreak.service.OpdbServiceEndpointCollectorTest.clusterWithOrchestrator(OpdbServiceEndpointCollectorTest.java:265)
	at com.sequenceiq.cloudbreak.service.OpdbServiceEndpointCollectorTest.createClusterWithComponents(OpdbServiceEndpointCollectorTest.java:272)
	at com.sequenceiq.cloudbreak.service.OpdbServiceEndpointCollectorTest.testPrepareClusterExposedServices(OpdbServiceEndpointCollectorTest.java:202)
...
Caused by: java.io.FileNotFoundException: class path resource [defaults/blueprints/7.2.0/cdp-opdb.bp] cannot be opened because it does not exist
	at org.springframework.core.io.ClassPathResource.getInputStream(ClassPathResource.java:199)
	at com.sequenceiq.cloudbreak.util.FileReaderUtils.readFileFromClasspath(FileReaderUtils.java:43)
	at com.sequenceiq.cloudbreak.service.OpdbServiceEndpointCollectorTest.clusterWithOrchestrator(OpdbServiceEndpointCollectorTest.java:262)
	... 72 more
```
* `expectedCount` in `com.sequenceiq.it.cloudbreak.testcase.mock.ClusterTemplateTest.testListDefaultClusterTemplate()` shall be fixed.

**Comment by lajosrodek** [comment]
Follow-up to  #12169.

**Comment by stoty** [comment]
Thanks, I've pushed the fixes (hopefully).
I could find the OpdbServiceEndpointCollectorTest error from the checks link, but not the other one. 
(The unit-test link lead to a missing jenkins page )

**Review by lajosrodek — APPROVED** [review]
Thanks for the fixes! LGTM

**Pull request merged**
