### PR TITLE
OPSAPS-52161. Avoid overwriting root krb5 ccache, speed up chown

### PR DESCRIPTION
**Pull request by toddlipcon**
This fixes the createuserhome.sh script (which is invoked once a minute
by cron) so that it no longer uses the default krb5 ticket cache
location. Instead it uses a cloudbreak-specific one. That means that it
won't interfere with any end user who might be trying to kinit on that
same node. This should fix some of our test cases which were doing that
same thing.

Along the way I noted that the existing 'chown' path was quite slow --
it took about 17 minutes to perform the chowns for 623 users (each one
takes about 2 seconds, sometimes slower). In contrast, using curl to
invoke webhdfs takes about 10ms per operation. The full sync for 623
users took 10 seconds.

### CODE REVIEW

**Comment by toddlipcon** [comment]
I tested this by scping the script to a distrox master node, removing /tmp/existing_users, and running it. I also tested modifying the script temporarily to put an 'x' in the middle of the path and saw that the error handling was working for FileNotFoundException (the error got output and the script exited). Also verified that it properly kinits into the new path and doesn't impact the default credential cache of the root user anymore.

**Comment by keyki** [comment]
It's a huge improvement, I think we should put this to rc-2.12 to release it with GA. @RamVenkatesh @akanto any objections?

**Comment by keyki** [comment]
Thanks @ddraj, @toddlipcon can you please change the base branch to rc-2.12?

**Comment by toddlipcon** [comment]
ok, base changed to 2.12.

**Pull request merged**
