### PR TITLE
CB-670 – resolve two Mappable implementation

### PR DESCRIPTION
**Pull request by gregito**
CB-670 – resolve two Mappable implementation

### CODE REVIEW

**Comment by keyki** [comment]
I think the voting will end with no `var` usage. Can you please fix those in your PR?

**Comment by gregito** [comment]
> I think the voting will end with no `var` usage. Can you please fix those in your PR?

then please merge it 🙃

**Comment by keyki** [comment]
> > I think the voting will end with no `var` usage. Can you please fix those in your PR?
> 
> then please merge it 🙃

Gergo approved so I can merge once the build finishes

**Comment by gregito** [comment]
> > > I think the voting will end with no `var` usage. Can you please fix those in your PR?
> > 
> > 
> > then please merge it 🙃
> 
> Gergo approved so I can merge once the build finishes

supercool 🎉 thanks!

**Pull request merged**
