### PR TITLE
CB-20289 CB Auth Connector ApiKeyRequestFilter is not working for V3 …

### PR DESCRIPTION
**Pull request by bbihari**
…format keys

### CODE REVIEW

**Review by aszegedi — APPROVED** [review]
GOV-Dev API E2E tests run again with V3 Secret Key. So the improvement has been done on this and working.

_**NOTE:**_
However test results are far from good, because of a new issue: `EnvironmentCreateAction: FreeIpa deployment requests are only allowed with at least '2' instance(s) by group. The requested value was '1'`. (So I've filed a new issue for this [CB-20412](https://jira.cloudera.com/browse/CB-20412). I hope more surprises are not coming...)

**Review by lnardai — APPROVED** [review]

**Comment by lacikaaa** [comment]
could you elaborate a bit more in the commit message about what is this change about? I see it's not working, but should this fix it and if yes how?

**Comment by aszegedi** [comment]
It seems need a little bit more deep-dive in the Cloudbreak, because of the latest test results:
```
[FlowEvent(flowId=3f054f8a-2cd8-4a02-8783-9a7ec7c04bad)] ENV_CREATION_FAILED_STATE - FreeIpa creation operation failed. Reason: 'INVALID_ARGUMENT: Invalid access key type ED25519 for this region.'
- [FlowEvent(flowId=3f054f8a-2cd8-4a02-8783-9a7ec7c04bad)] FREEIPA_CREATION_STARTED_STATE - FreeIpa creation operation failed. Reason: 'INVALID_ARGUMENT: Invalid access key type ED25519 for this region.'
- [Notification] SENT - Environment creation failed
...
```
This is the case for all the FreeIPA create.

**Comment by bbihari** [comment]
> 

@lacikaaa  this is the first step fixing the gov test runs, without this change the cb clients are not working because they generate the signature in the requests with a wrong method

**Pull request merged**
