### PR TITLE
CB-22154 Change the extra host group names in EDL from <service>HG to…

### PR DESCRIPTION
**Pull request by RokolyA94**
<service>_scale_out, which more readable to the customer

### CODE REVIEW

**Comment by doktoric** [comment]
this should go to the next release. Risky change..

**Comment by kkalvagadda1** [comment]
> this should go to the next release. Risky change..

All these changes are related to EDL. This PR has updated the names of extra hostgroups nothing more. Why do you think it is risky?
We disabled EDL on the PROD to get the names right before customers can use it.

**Review by kkalvagadda1 — APPROVED** [review]

**Review by votez — APPROVED** [review]

**Comment by lnardai** [comment]
@RokolyA94 Can you squash the commits?

**Comment by keyki** [comment]
This goes to 2.73 is this the correct branch?

**Comment by lnardai** [comment]
retest this please!

**Pull request merged**
