### PR TITLE
CB-6844: Start freeipahealthagent after backups during install

### PR DESCRIPTION
**Pull request by holleyism**
Moved the starting of the freeipa healthagent to after backups.
Also minor unrelated change for logging.

This should not be merged until a new AMI for FreeIPA is published.

### CODE REVIEW

**Comment by wonderslug** [comment]
Need to reopen to get cert tracking

**Comment by akanto** [comment]
Is this still relevant?

**Comment by wonderslug** [comment]
Yes im working on it now

**Comment by wonderslug** [comment]
These changes are going into another PR.

**Pull request closed without merging**
