### PR TITLE
CB-18420 Set property nifi.nar.hotfix.provider.enabled=true via clust…

### PR DESCRIPTION
**Pull request by vbrodetskyi**
…er template. Set this property with true value, enables resource fetcher functionality. We need that for 7.2.16.

See detailed description in the commit message.

### CODE REVIEW

**Review by doktoric — APPROVED** [review]

**Comment by vbrodetskyi** [comment]
@doktoric could you please clarify, is it enough to commit this change into master branch to make it available in 7.2.16? Thanks.

**Review by lajosrodek — APPROVED** [review]
LGTM

**Comment by lajosrodek** [comment]
@vbrodetskyi CB releases are not tied to runtime versions. `master` branch is 2.63 at the moment. Given that 2.62 was just got branched last week prior to the unplug and its QE verification has not yet started, it will likely take 2-3 weeks to have 2.62 promoted to Prod, and another similar 2-3 weeks for 2.63. So the present change will likely land in Prod around the end of September / early October. I do not know how this compares to the 7.2.16 release schedule, though.

**Comment by vbrodetskyi** [comment]
@lajosrodek got it, thank you. For me, it's important to have this change available for 7.2.16, because we will have related CFM change for Flow Datahub cluster on 7.2.16. Do you know who can clarify on that?

**Comment by lajosrodek** [comment]
@TheTinkerDad Do you possibly know if 7.2.16 is targeting CB 2.63? (It is definitely not available for 2.61, but I have not checked 2.62 TBH.)

**Pull request merged**
