### PR TITLE
[RMP-9448] moving superset as seperate service from the druid template

### PR DESCRIPTION
**Pull request by b-slim**
As part of 2.6.3 (M20) superset will be separate service independent from druid. This PR does the required changes to pull out superset as a separate service.

### CODE REVIEW

**Comment by ashutoshc** [comment]
@doktoric @RamVenkatesh  who is right person to review this?

**Comment by doktoric** [comment]
@ashutoshc @b-slim how can I test this feature? Is 2.6.3 availablefor testing?

**Comment by b-slim** [comment]
yes current hdp 2.6.3  internal build has superset as separate service.

**Comment by doktoric** [comment]
@b-slim ok then I will test this tomorrow. Thanks!

**Comment by b-slim** [comment]
@doktoric  this is the bug number https://hortonworks.jira.com/browse/BUG-81231

**Comment by doktoric** [comment]
@b-slim can you please provide me the ambari and hdp repo url for testing ?

**Comment by ashutoshc** [comment]
Any latest build will work.
e.g,
#VERSION_NUMBER=2.6.3.0-110
[HDP-2.6.3.0-110]
name=HDP Version - HDP-2.6.3.0-110
baseurl=http://s3.amazonaws.com/dev.hortonworks.com/HDP/centos7/2.x/BUILDS/2.6.3.0-110
gpgcheck=1
gpgkey=http://s3.amazonaws.com/dev.hortonworks.com/HDP/centos7/2.x/BUILDS/2.6.3.0-110/RPM-GPG-KEY/RPM-GPG-KEY-Jenkins
enabled=1
priority=1


[HDP-UTILS-1.1.0.21]
name=HDP-UTILS Version - HDP-UTILS-1.1.0.21
baseurl=http://s3.amazonaws.com/dev.hortonworks.com/HDP-UTILS-1.1.0.21/repos/centos7
gpgcheck=1
gpgkey=http://s3.amazonaws.com/dev.hortonworks.com/HDP/centos7/2.x/updates/2.6.3.0/RPM-GPG-KEY/RPM-GPG-KEY-Jenkins
enabled=1
priority=1

#VERSION_NUMBER=2.6.0.0-129
[ambari-2.6.0.0-129]
name=ambari Version - ambari-2.6.0.0-129
baseurl=http://s3.amazonaws.com/dev.hortonworks.com/ambari/centos7/2.x/BUILDS/2.6.0.0-129
gpgcheck=1
gpgkey=http://s3.amazonaws.com/dev.hortonworks.com/ambari/centos7/2.x/BUILDS/2.6.0.0-129/RPM-GPG-KEY/RPM-GPG-KEY-Jenkins
enabled=1
priority=1

**Comment by biharitomi** [comment]
Hi @b-slim ,

Thanks for the contribution. Your change was not backward compatible so we decided to create the fix in an other [PR](https://github.com/hortonworks/cloudbreak/pull/2898) based on your changes. We needed these changes/fix in a hurry because our integration tests are failing due to use HDP 2.6.3.0 by default.

Thanks,
Tamas

**Pull request closed without merging**
