### PR TITLE
CB-9878 Rename master to main for DL HA.

### PR DESCRIPTION
**Pull request by orngejaket**
See detailed description in the commit message.

### CODE REVIEW

**Review by kmanamcheri — COMMENTED** [review]
You had mentioned that there are lots of occurrences of the string "master". Should we search for comments etc and update them (at least in the data lake service areas)?

**Comment by orngejaket** [comment]
Yea there's 3000+ occurrences of the word master in the code base.  So it's unlikely for me to find them all.  Some are part of error messages, others are part of the lightduty int tests.  So there's no telling what affects this could have, however since ha is new, it's shouldn't break anything.  I've also been able to create a datahub and run queries against it with no issue.

**Comment by doktoric** [comment]
I suggest to add main to aws-vm-recommendation.json and azure-vm-recommendation.json

**Review by lacikaaa — CHANGES_REQUESTED** [review]
I can't find any info regarding the motivation and benefit for the renaming neither in the commit message nor in the jira description. Could you add some details if possible to both of them?

**Comment by doktoric** [comment]
do we still need this?

**Pull request closed without merging**
