### PR TITLE
BUG-98277 Fetch network interfaces to select gateway

### PR DESCRIPTION
**Pull request by mhmxs**

### CODE REVIEW

**Comment by mhmxs** [comment]
@leki75

**Comment by keyki** [comment]
There are many salt states where eth0 is hardcoded, like this:
```
{% set has_public_address = salt['pillar.get']('hosts')[salt['network.interface_ip']('eth0')]['public_address'] %}
```

**Comment by leki75** [comment]
I will upload a separate pull request to eliminate eth0 hardcoded.

**Comment by mhmxs** [comment]
@leki75 Could you please create your pull request on top of this one? So we should merge both of them at the same time.

**Comment by leki75** [comment]
No problem.

**Pull request closed without merging**
