### PR TITLE
CB-11992:  Add zookeeper service to Datamart templates for 7.2.9 and …

### PR DESCRIPTION
**Pull request by doktoric**
…later

    Add instance of zookeeper service as required by Knox

See detailed description in the commit message.

### CODE REVIEW

**Comment by kmanamcheri** [comment]
@doktoric please make this template change for 7.2.10 as well. I found a few more issues where we made changes to 7.2.9 but didn't make it in 7.2.10 and we run into problems again.

**Comment by doktoric** [comment]
@drorke @smolnar82 do we need this for 7.2.10 ?

**Comment by smolnar82** [comment]
@lmccay We need this for 7.2.9, right?

**Comment by smolnar82** [comment]
@doktoric Is your question if we need ZK for Knox in future releases? I believe the answer is yes.

**Comment by drorke** [comment]
The commit already updates the 7.2.10 version of the blueprint (in addition to 7.2.9).  Is there anything else that would need to be done to get it into 7.2.10?

**Comment by lmccay** [comment]
> @lmccay We need this for 7.2.9, right?

Yes, this is required for 7.2.9 for UBS token based access to JDBC. It is customer committed and needs the storage durability provided by ZK.

**Comment by kmanamcheri** [comment]
To reiterate the plan, this is not a blocker for 2.41. This is a blocker for 7.2.9. CB 2.41 is currently in promotion stages and once that goes out, we'll merge this and get this out as a hotfix to support 7.2.9.

**Pull request closed without merging**
