### PR TITLE
CB-10901 Subnet should not be public by the main route table in case of a route table is associated explicitly.

### PR DESCRIPTION
**Pull request by pkedvessy**
See detailed description in the commit message.

### CODE REVIEW

**Review by biharitomi — APPROVED** [review]
LGTM, thanks!

**Comment by pkedvessy** [comment]
retest this please

**Review by keyki — CHANGES_REQUESTED** [review]
We will merge the change once 2.37 is landed on prod and we can start the hotfix process.

**Comment by keyki** [comment]
@pkedvessy we decided to merge this PR to master instead of 2.37. Can you please set the target branch to master?

**Pull request merged**
