### PR TITLE
CB-11556 - extract code duplication from delete flow exception handlings

### PR DESCRIPTION
**Pull request by gregito**

### CODE REVIEW

**Comment by lajosrodek** [comment]
@gregito  Erm, there is one more handler to take care of. 😃 Please [ResourceEncryptionDeleteHandler.accept()](https://github.com/hortonworks/cloudbreak/blob/master/environment/src/main/java/com/sequenceiq/environment/environment/flow/deletion/handler/ResourceEncryptionDeleteHandler.java#L68-L78) that got merged in yesterday (#10407).

Speaking of which, `deleteEncryptionResources()` of said class seems to simply swallow the exception in the `catch` clause; this apparently slipped through our rushed reviews. 😞 

CC @doktoric @juhi-09

**Comment by lajosrodek** [comment]
@gregito Thanks for the change. I believe `ResourceEncryptionDeleteHandlerTest` has a test case checking the error path as well, and probably fails with an NPE due to the missing `HandlerExceptionProcessor` dependency.

**Comment by lajosrodek** [comment]
Looks like there is also one more class with duplication: [IdBrokerMappingsDeleteHandler](https://github.com/hortonworks/cloudbreak/blob/master/environment/src/main/java/com/sequenceiq/environment/environment/flow/deletion/handler/IdBrokerMappingsDeleteHandler.java).

**Review by bergerdenes — CHANGES_REQUESTED** [review]
I had some private questions: `HandlerFailureConjoiner` could take `Event` only
and  when verifying `mockExceptionProcessor`, the instances of the `HandlerFailureConjoiner` could be captured with an `ArgumentCaptor` and check the values of it

**Review by afarsang — APPROVED** [review]

**Review by doktoric — APPROVED** [review]

**Pull request merged**
