### PR TITLE
CB-10844 CM launched on Gateway in Flow Management Light/Heavy duty t…

### PR DESCRIPTION
**Pull request by vbrodetskyi**
…emplates. Changed 'gateway' node name to 'management', according to customer request.

See detailed description in the commit message.

### CODE REVIEW

**Review by lajosrodek — APPROVED** [review]
LGTM

**Comment by vbrodetskyi** [comment]
@lajosrodek @doktoric should i also merge this change to some other branches or master will be enough?

**Comment by lajosrodek** [comment]
@vbrodetskyi `master` (v2.38 at the moment) is sufficient if you are fine with having it only from CB 2.38 onwards. Otherwise, it would have to be pushed directly into some release branch and then rolled out as a Prod Hotfix. 😃 

Holding back with merging until someone from CB can also approve.

**Comment by vbrodetskyi** [comment]
@lajosrodek thank you for clarification, according to fix version in jira https://jira.cloudera.com/browse/CB-10844, it should be i 2.38, so looks like master branch should be enough.

**Review by doktoric — APPROVED** [review]

**Pull request merged**
