### PR TITLE
CB-13866 Do deploy client config and refresh cluster command after sc…

### PR DESCRIPTION
**Pull request by horadla23**
…ale up

See detailed description in the commit message.

### CODE REVIEW

**Comment by horadla23** [comment]
retest this please

**Comment by horadla23** [comment]
retest this please

**Comment by horadla23** [comment]
Current behaviour (tested on mow-dev with 7.2.12 SDX):
DE scale up, 1 node, worker group:
Screenshot from 2021-10-01 13-44-59
Screenshot from 2021-10-01 13-44-39
Nifi scale up, 1 node, nifi_scaling group:
Screenshot from 2021-10-01 12-58-08
g)

**Comment by horadla23** [comment]
New behavior, tested locally with 7.2.12 SDX:
DE scale up, 1 node, worker group:
Screenshot from 2021-10-01 14-12-21
Screenshot from 2021-10-01 14-12-33

**Comment by horadla23** [comment]
New behavior, tested locally with 7.2.12 SDX:
Nifi scale up, 1 node, nifi_scaling group (management node modified based on steps provider by Vitaly in the ticket):
Screenshot from 2021-10-01 14-47-45
Screenshot from 2021-10-01 14-48-05

**Review by lturcsanyi — APPROVED** [review]

**Pull request merged**
