### PR TITLE
CB-14152. Update cdp-telemetry desired version to avoid including roo…

### PR DESCRIPTION
**Pull request by oleewere**
…t folder in compressed bundles

See detailed description in the commit message.

### CODE REVIEW

**Comment by lnardai** [comment]
I don't see the urgency here, or did we introduce this as a bug in 2.47? If it was always working like this and there is no function impatirty we should only merge this to master.

**Comment by oleewere** [comment]
@lnardai this is regression that is fixed in that 0.4.15 version (introduced in 0.4.14 - that version is available from 2.48), not worked like this, EDH won't be able to process bundles, so.diagnostics cannot be re-enabled without this in 2.48

**Review by lnardai — APPROVED** [review]

**Comment by lnardai** [comment]
QA just started validation, but according to JIRA the ticket was opened on last Friday but it's not marked as blocking. So we knew the release was not ready. Now we need to explain to QA again why the version they validated is not the correct one. These are the things that make the release long.
Please link it to corresponding PROM ticket(PROM-6) ticket next time.

**Comment by oleewere** [comment]
@lnardai note that i will need to enable the diagnostics entitlement on mow-int so re run tests will be needed anyway. (or will expect different results, as some of the test failures were expected because of disabling diagnostics)

**Comment by lnardai** [comment]
Is this behind entitlement on Prod as well?

**Pull request merged**
