### PR TITLE
Merge CB-18996

### PR DESCRIPTION
**Pull request by attilabukor**
See detailed description in the commit message.

### CODE REVIEW

**Review by lajosrodek — APPROVED** [review]
LGTM

**Comment by lajosrodek** [comment]
CI job failures are due to the temporary unavailability of `repo.hortonworks.com`:
```
Note: Recompile with -Xlint:unchecked for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':cloud-azure:compileJava'.
> Could not resolve all files for configuration ':cloud-azure:compileClasspath'.
   > Could not resolve net.minidev:json-smart:[1.3.2,2.4.2].
     Required by:
         project :cloud-azure > com.microsoft.azure:azure-client-authentication:1.7.14 > com.microsoft.azure:adal4j:1.6.7 > com.nimbusds:oauth2-oidc-sdk:9.4
      > Failed to list versions for net.minidev:json-smart.
         > Unable to load Maven meta-data from https://repo.hortonworks.com/content/repositories/releases/net/minidev/json-smart/maven-metadata.xml.
            > Could not HEAD 'https://repo.hortonworks.com/content/repositories/releases/net/minidev/json-smart/maven-metadata.xml'. Received status code 502 from server: Bad Gateway

* Try:
```
Retriggering them.

**Comment by attilabukor** [comment]
checkstyle-test failed, I tried it on my machine and it worked. Should I retest it?

**Comment by lajosrodek** [comment]
`checkstyle-test ` error:
```
> Task :sdx-connector:compileJava
/grid/0/jenkins/workspace/workspace/cloudbreak-pull-request-builder-checkstyle-test/sdx-connector/src/generated/main/grpc/com/cloudera/thunderhead/service/sdxsvcadmin/SDXSvcAdminGrpc.java:2486: error: incompatible types: inference variable RespT#1 has incompatible equality constraints RegisterAwsObjectStorageRootRequest,RespT#2,RegisterAwsObjectStorageRootResponse
          .addMethod(
                    ^
  where RespT#1,ReqT#1,RespT#2,ReqT#2 are type-variables:
    RespT#1 extends Object declared in method <ReqT#1,RespT#1>addMethod(MethodDescriptor<ReqT#1,RespT#1>,ServerCallHandler<ReqT#1,RespT#1>)
    ReqT#1 extends Object declared in method <ReqT#1,RespT#1>addMethod(MethodDescriptor<ReqT#1,RespT#1>,ServerCallHandler<ReqT#1,RespT#1>)
    RespT#2 extends Object declared in method <ReqT#2,RespT#2>asyncUnaryCall(UnaryMethod<ReqT#2,RespT#2>)
    ReqT#2 extends Object declared in method <ReqT#2,RespT#2>asyncUnaryCall(UnaryMethod<ReqT#2,RespT#2>)
...
> Task :sdx-connector:compileJava
1 error

> Task :sdx-connector:compileJava FAILED
...
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sdx-connector:compileJava'.
> Compilation failed; see the compiler error output for details.
...
BUILD FAILED in 8m 27s
```

**Comment by lajosrodek** [comment]
@attilabukor The `:sdx-connector:compileJava` failure in `checkstyle-test` is likely some CI slave issue; the very same target completed successfully for the other CI jobs. I just retriggered `checkstyle-test`, it will hopefully succeed this time. :smile:

**Pull request merged**
