### PR TITLE
ODX-684 Move hadoop.tmp.dir out of /tmp

### PR DESCRIPTION
**Pull request by anmolnar**
Added new `hadoop.tmp.dir` setting to all COD specific blueprints.

### CODE REVIEW

**Comment by doktoric** [comment]
the only thing here is that it will not work on ycloud.

**Comment by anmolnar** [comment]
@doktoric Do you know a good way to overcome that?

**Comment by anmolnar** [comment]
@doktoric I'm done with the changes that we discussed.

**Comment by doktoric** [comment]
retest this please

**Review by doktoric — APPROVED** [review]

**Pull request merged**
